export type IpoCalendarEntry = {
  slug?: string;
  company: string;
  market: "Mainboard" | "SME";
  opens: string;
  closes: string;
  issueSizeCr: number | null;
  priceBand: string | null;
  exchange?: "BSE SME" | "NSE SME";
};

export type IpoWeek = {
  id: 1 | 2 | 3 | 4;
  label: string;
  range: string;
  entries: IpoCalendarEntry[];
};

// Source snapshot: Chittorgarh Mainboard and SME IPO calendars, accessed
// 16 August 2026; exchange status refreshed 19 August 2026. Entries are grouped
// by opening date. A null means no final figure and must never render as zero.
const august2026Ipos: IpoCalendarEntry[] = [
  { company: "Anawil Wire & Engineering", slug: "anawil-wire-engineering-ipo", market: "SME", opens: "2026-08-03", closes: "2026-08-05", issueSizeCr: 177.81, priceBand: "₹257–₹270", exchange: "NSE SME" },
  { company: "Aegeus Technologies", slug: "aegeus-technologies-ipo", market: "SME", opens: "2026-08-04", closes: "2026-08-06", issueSizeCr: 23.71, priceBand: "₹100–₹105", exchange: "BSE SME" },
  { company: "Ardee Industries", slug: "ardee-industries-ipo", market: "Mainboard", opens: "2026-08-05", closes: "2026-08-07", issueSizeCr: 425.87, priceBand: "₹50–₹53" },
  { company: "LAPL Automotive", slug: "lapl-automotive-ipo", market: "SME", opens: "2026-08-06", closes: "2026-08-10", issueSizeCr: 32.40, priceBand: "₹88–₹94", exchange: "BSE SME" },
  { company: "LEAP India", slug: "leap-india-ipo", market: "Mainboard", opens: "2026-08-07", closes: "2026-08-11", issueSizeCr: 2480, priceBand: "₹151–₹159" },
  { company: "Technocraft Ventures", slug: "technocraft-ventures-ipo", market: "Mainboard", opens: "2026-08-07", closes: "2026-08-11", issueSizeCr: 251.88, priceBand: "₹200–₹212" },
  { company: "Optimystix Entertainment India", slug: "optimystix-entertainment-india-ipo", market: "SME", opens: "2026-08-07", closes: "2026-08-11", issueSizeCr: 108.50, priceBand: "₹166–₹175", exchange: "NSE SME" },

  { company: "Dhoot Transmission", slug: "dhoot-transmission-ipo", market: "Mainboard", opens: "2026-08-10", closes: "2026-08-12", issueSizeCr: 3066.89, priceBand: "₹829–₹871" },
  { company: "Molbio Diagnostics", slug: "molbio-diagnostics-ipo", market: "Mainboard", opens: "2026-08-10", closes: "2026-08-12", issueSizeCr: 939.7, priceBand: "₹768–₹807" },
  { company: "Milky Mist Dairy Food", slug: "milky-mist-dairy-food-ipo", market: "Mainboard", opens: "2026-08-11", closes: "2026-08-13", issueSizeCr: 1553, priceBand: "₹133–₹140" },
  { company: "Sham Foam", slug: "sham-foam-ipo", market: "SME", opens: "2026-08-11", closes: "2026-08-13", issueSizeCr: 40.48, priceBand: "₹130", exchange: "BSE SME" },
  { company: "Fascinate Textiles", slug: "fascinate-textiles-ipo", market: "SME", opens: "2026-08-11", closes: "2026-08-19", issueSizeCr: 66.98, priceBand: "₹148–₹156", exchange: "NSE SME" },
  { company: "Shiprocket", slug: "shiprocket-ipo", market: "Mainboard", opens: "2026-08-12", closes: "2026-08-14", issueSizeCr: 1617.48, priceBand: "₹92–₹97" },
  { company: "Behari Lal Engineering", slug: "behari-lal-engineering-ipo", market: "Mainboard", opens: "2026-08-12", closes: "2026-08-14", issueSizeCr: 301.62, priceBand: "₹271–₹285" },
  { company: "Q&T Foods", slug: "qt-foods-ipo", market: "SME", opens: "2026-08-12", closes: "2026-08-14", issueSizeCr: 26.25, priceBand: "₹115", exchange: "BSE SME" },
  { company: "Pramodini Medicare", slug: "pramodini-medicare-ipo", market: "SME", opens: "2026-08-12", closes: "2026-08-14", issueSizeCr: 69.04, priceBand: "₹110–₹118", exchange: "NSE SME" },
  { company: "Credent Connect N Care", slug: "credent-connect-n-care-ipo", market: "SME", opens: "2026-08-13", closes: "2026-08-17", issueSizeCr: 93.90, priceBand: "₹179–₹189", exchange: "NSE SME" },
  { company: "Skytech Infinite Platform", slug: "skytech-infinite-platform-ipo", market: "SME", opens: "2026-08-14", closes: "2026-08-18", issueSizeCr: 22.68, priceBand: "₹73–₹77", exchange: "NSE SME" },
  { company: "ENS Enterprises", slug: "ens-enterprises-ipo", market: "SME", opens: "2026-08-14", closes: "2026-08-18", issueSizeCr: 33.14, priceBand: "₹87–₹92", exchange: "BSE SME" },
  { company: "Technocrats Plasma Systems", slug: "technocrats-plasma-systems-ipo", market: "SME", opens: "2026-08-14", closes: "2026-08-18", issueSizeCr: 60.98, priceBand: "₹125–₹132", exchange: "BSE SME" },

  { company: "Lalithaa Jewellery Mart", slug: "lalithaa-jewellery-mart-ipo", market: "Mainboard", opens: "2026-08-17", closes: "2026-08-19", issueSizeCr: 1700, priceBand: "₹190–₹201" },
  { company: "Horizon Industrial Parks", slug: "horizon-industrial-parks-ipo", market: "Mainboard", opens: "2026-08-17", closes: "2026-08-19", issueSizeCr: 2600, priceBand: "₹57–₹60" },
  { company: "Shankesh Jewellers", slug: "shankesh-jewellers-ipo", market: "Mainboard", opens: "2026-08-18", closes: "2026-08-20", issueSizeCr: 367.18, priceBand: "₹88–₹93" },
  { company: "Sunshine Pictures", slug: "sunshine-pictures-ipo", market: "Mainboard", opens: "2026-08-18", closes: "2026-08-20", issueSizeCr: 282.14, priceBand: "₹342–₹360" },
  { company: "Gaja Alternative Asset Management", slug: "gaja-alternative-asset-management-ipo", market: "Mainboard", opens: "2026-08-19", closes: "2026-08-21", issueSizeCr: 550, priceBand: "₹152–₹160" },
  // Skyways Air Services removed: its March 2026 RHP launch was deferred and no August dates were verified as of 14 August 2026.
];

const weekForDate = (date: string): 1 | 2 | 3 | 4 => {
  const day = Number(date.slice(-2));
  if (day <= 7) return 1;
  if (day <= 14) return 2;
  if (day <= 21) return 3;
  return 4;
};

const weekMeta = [
  { id: 1 as const, label: "Week 1", range: "1–7 August" },
  { id: 2 as const, label: "Week 2", range: "8–14 August" },
  { id: 3 as const, label: "Week 3", range: "15–21 August" },
  { id: 4 as const, label: "Week 4", range: "22–31 August" },
];

export const august2026Weeks: IpoWeek[] = weekMeta.map((week) => ({
  ...week,
  entries: august2026Ipos.filter((entry) => weekForDate(entry.opens) === week.id),
}));

export const august2026Snapshot = {
  asOf: "19 August 2026",
  coverageCount: 25,
  verificationNotes: [
    "All 25 companies currently shown in the August calendar link to an individual analysis page.",
    "NSE continued to classify Shankesh Jewellers and Sunshine Pictures active at the approximately 8:04 p.m. IST 18 August recheck after their completed anchor books: BSE notices 20260817-31 and 20260817-32 confirm ₹110.15 crore and ₹84.64 crore of anchor allocations respectively at the upper offer prices. BSE's official 5:00 p.m. day-one category books showed Shankesh at 34,04,960 bids, or 0.1232×, with QIB 0.0041×, NII 0.2823× and retail 0.1231×; Sunshine recorded 63,10,392 bids, or 1.1503×, with QIB 0.0206×, NII 1.9540× and retail 1.4513×. NSE's current-issue endpoint separately displayed 64,71,840 Shankesh bids, or 0.2342×, and 1,74,64,319 Sunshine bids, or 3.1834×. The official exchange views are kept separate and not added because their aggregation basis is not confirmed; all are preliminary day-one readings and the issues remain open through 20 August.",
    "BSE's official listing notices and historical-price files now add first-day context for two BSE SME listings. Aegeus traded under scrip 544858 on 11 August, opening at ₹124.50 and closing at ₹130.70 versus its ₹105 issue price; LAPL traded under scrip 544863 on 13 August, opening at ₹135 and closing at ₹128.29 versus ₹94. Both were in the trade-for-trade segment and recorded 100% delivery in BSE's files. These dated outcomes are market context, not recommendations.",
    "NSE's official security files add first-day context for two NSE Emerge listings: Anawil opened at ₹329.65 and closed at ₹346.10 on 10 August versus its ₹270 issue price; Optimystix opened at ₹180 and closed at ₹189 on 14 August versus ₹175. The Optimystix page previously showed ₹175 as the opening price and has been corrected. Aegeus's final RHP now also supplies workforce attrition, nil contingent liabilities and the FY25 audit-trail exception.",
    "NSE's official security files now supply first-day trading context for three Mainboard listings: Ardee opened at ₹72.00 and closed at ₹67.12 on 12 August versus its ₹53 issue price; LEAP India opened at ₹165.90 and closed at ₹144.93 on 14 August versus ₹159; Technocraft Ventures opened at ₹284.00 and closed at ₹311.15 on 14 August versus ₹212. These historical listing outcomes are presented as dated market context, not recommendations.",
    "An 18 August final-RHP depth pass adds balance-sheet evidence to Ardee Industries, LEAP India and Technocraft Ventures. Ardee's ₹84.58 crore supplier advances, nil receivable allowance, ₹12.76 crore contingent liabilities and guarantee-linked cash balances sharpen its cash-conversion analysis. LEAP's page now maps ₹1,480.74 crore of PPE, ₹133.57 crore of lease liabilities and the 15%–25% residual-value assumptions used for pooling assets. Technocraft's working-capital object has been corrected from ₹138 crore to the RHP's ₹150 crore; its page also separates roughly ₹100 crore of current other financial assets plus long-term retention from trade receivables and records ₹9.98 crore of disputed contingent claims.",
    "Dhoot Transmission's final RHP confirms ₹1,400 crore of fresh issue and 1,91,37,602 OFS shares, implying an approximately ₹3,066.89 crore total offer at the ₹871 final price. BSE notice 20260814-32 confirms 13 August allotment, 20,45,48,057 post-issue shares and listing from 17 August under scrip 544867 / DHOOTTRANS. NSE's archived first-day file records a ₹1,200 open, ₹1,131–₹1,205 range and ₹1,187.05 close; the 18 August close was ₹1,305.75, equal to that session's high and 49.91% above issue price. BSE and NSE prints are kept exchange-specific. The analysis also covers FY26 customer concentration, employee attrition and the auditor's accounting-software audit-trail exceptions.",
    "Molbio Diagnostics' final RHP confirms a ₹200 crore fresh issue plus 91.66 lakh OFS shares, or approximately ₹939.70 crore at the ₹807 final price. BSE notice 20260814-42 confirms 13 August allotment, 11,52,39,996 post-issue shares and listing from 17 August under scrip 544866 / MOLBIO. NSE's archived first-day file records a ₹980 open, ₹926.35–₹1,064.75 range and ₹1,041.70 close; the 18 August close was ₹1,110.90, 37.66% above issue price. BSE and NSE prints are kept exchange-specific. Its analysis quantifies ₹168.74 crore of FY26 contingent liabilities, weaker cash conversion and employee attrition; the 7 August addendum's pre-offer promoter transfer remains separately disclosed.",
    "Ardee Industries, Anawil Wire and Aegeus Technologies have been reworked against their final RHPs. The largest correction is Anawil: its ₹177.81 crore offer comprised ₹142.69 crore fresh capital and ₹35.12 crore OFS, not an all-fresh issue, and the minimum individual bid was 800 shares. Aegeus's minimum application was likewise corrected to 2,400 shares; all three pages now include prospectus cash flow, working-capital and customer-concentration evidence.",
    "Gaja Alternative Asset Management's 12 August RHP, price advertisement and BSE issue record 7895 confirm a ₹550 crore offer: ₹450 crore fresh issue, ₹100 crore OFS, ₹152–₹160 band, 93-share lot and 19–21 August bidding. BSE notice 20260818-38 confirms a 1,03,12,500-share anchor allocation at ₹160, worth ₹165.00 crore and equal to 30.00% of the 3,43,75,000-share cap-price offer. The cap-price illustration leaves 2,40,62,500 post-anchor shares. At the approximately 12:36 a.m. IST 19 August checkpoint, NSE marked the issue Active but showed zero offered shares and bids; BSE's untimestamped pre-open table showed zero bids against 2,53,28,946 shares. These are pre-market states, not demand readings. The BSE denominator uses the floor-price maximum and is not blended with the cap-price illustration. The issue record still showed no addendum or corrigendum. ₹372 crore, or 82.7% of fresh proceeds, is allocated to sponsor commitments and the related bridge repayment across FY27–FY29. The deeper balance-sheet review separates ₹131.47 crore of trade receivables with no impairment allowance, ₹271.93 crore of alternative-fund investments, ₹58.58 crore of uncalled commitments, ₹26.69 crore of advances recoverable in cash and ₹2.64 crore explicitly tagged as carried-interest receivable. It now also quantifies 15.61 lakh outstanding ESOPs, their concentration in one senior employee and the FY24 reclassification of ₹18.40 crore of carried interest from other income to operating revenue without changing total income or profit.",
    "Skyways Air Services is not included: its March 2026 RHP launch was deferred, and no primary filing confirming an August relaunch was found.",
    "Technocrats Plasma's issuer-hosted RHP confirms 46,20,000 fresh shares and 14–18 August bidding. BSE notice 20260813-18 confirms 13,14,000 anchor shares at ₹132. BSE's official 5:00 p.m. IST post-close category book records 62,55,75,000 bids against its 33,06,000-share post-anchor display, or 189.2241×. The category readings are 169.5359× QIB, 231.3513× NII and 176.0455× retail. Because the display still includes the 2,31,000-share market-maker reservation, the same demand is approximately 203.44× the residual 30,75,000-share public pool by calculation. This is the latest official close book; issue-price, allotment and listing reconciliation remain pending. The page connects cost-to-cost project revenue recognition with ₹26.08 crore of work-in-progress, records no doubtful allowance despite ₹7.55 crore of receivables over six months, and marks quantified warranty provisioning as unavailable. It also covers 50.08% owned-capacity utilisation, 38.81% attrition, 93.50% top-ten supplier concentration, no business-interruption insurance, FY23 audit qualifications and pending Section 454 adjudications. The latest pass adds 90.8% secured fund-based utilisation, 11.35% cash-credit and 11.50% term-loan costs and the absence of a quantified order book. A deeper working-capital and governance pass now shows supplier advances plus other current assets jumping 15.3× to ₹14.55 crore, customers served falling from 273 to 180 despite 166% revenue growth, ₹1.50 crore of promoter loans settled through shares and ₹1.54 crore adjusted with a relative-owned firm. BSE exposes an addendum path, and the issuer site now supplies the readable 12 June addendum to the DRHP. That document says its changes would be incorporated into the later RHP, so it is treated as historical support rather than a new post-RHP correction.",
    "Technocrats Plasma's BSE price-demand curve, timestamped 7:04:52 p.m. IST on 18 August, records 62,35,28,000 cumulative shares at the ₹132 cap versus 62,55,75,000 at the ₹125 floor. The derived 99.67% ratio shows limited price drop-off inside the submitted book, but it is not a final issue-price or allotment confirmation.",
    "Shankesh Jewellers' official 11 August price-band advertisement verifies the ₹88–₹93 band, 160-share lot, 3,94,82,000-share offer and 18–20 August bidding. BSE notice 20260817-31 confirms 1,18,44,600 anchor shares at ₹93, worth approximately ₹110.15 crore; NSE and BSE display a 2,76,37,400-share post-anchor public pool. BSE's official 5:00 p.m. IST day-one category book showed 34,04,960 bids, or 0.1232×, with QIB 0.0041×, NII 0.2823× and retail 0.1231×. NSE's current-issue endpoint separately still displayed 64,71,840 bids, or 0.2342×, at the approximately 8:04 p.m. recheck; the exchange views are not combined. BSE issue record 7889 also corrected its earlier one-share placeholder to the official 160-share lot and contained no addendum or corrigendum at the recheck. The final RHP shows 97.6% utilisation of the ₹167 crore working-capital line at 30 June, a ₹360.53 crore FY26 gap and a projected ₹401.17 crore FY27 gap after the proposed ₹158 crore debt repayment. The operating review includes job-worker attrition, unsigned job-worker agreements, contingent liabilities, bullion-hedging margin balances and secured borrowing terms.",
    "Skytech Infinite Platform's official price advertisement confirms a ₹73–₹77 band and a 3,200-share minimum bid, equal to ₹2,33,600–₹2,46,400. NSE's approximately 9:35 p.m. IST 18 August current-issue feed still marked the issue Active after its scheduled bidding period and showed 58,57,600 bids against the 29,45,600-share displayed gross offer, or 1.99×. Because the displayed denominator includes the 1,48,800-share market-maker reservation, the same demand is approximately 2.09× the residual 27,96,800-share public pool by calculation. At the approximately 11:40 p.m. IST recheck, Skytech had left the current feed but was still absent from NSE's official past-issues table. That is an exchange transition, not a reconciled or category-wise book; final price and listing remain unavailable. Its final RHP allocates up to ₹16.81 crore to working capital, records 98.8% utilisation of the sanctioned fund-based line and assumes debtor days improve from 196 to 110. The page records nil doubtful-debt allowance despite ₹4.94 crore aged beyond six months, ₹0.75 crore disputed beyond three years, a ₹50.11 lakh FY26 director-loan balance and a 7.45% PNB cash-credit facility secured by stock, receivables, an equitable mortgage and promoter guarantees. It now also separates the 83.91% existing-customer revenue share from contractual backlog, maps the ₹8.66 crore inventory by raw material, work-in-progress and finished goods and quantifies 84.56% procurement concentration across three states. The latest contract and governance review clarifies that AMCs are generally only one year, records 1.22% FY26 employee attrition and flags that none of the directors had prior listed-company directorship experience.",
    "ENS Enterprises closed its ₹87–₹92 book on 18 August. BSE notice 20260813-19 confirms 10,26,000 anchor shares at ₹92, worth ₹9.44 crore. BSE's official 5:00 p.m. IST category book records 3,15,68,400 bids against its 25,76,400-share post-anchor display, or 12.2529×. The category readings are 9.4368× QIB, 17.1813× NII and 11.0020× retail. Because the display still includes the 1,81,200-share market-maker reservation, the same demand is approximately 13.18× the residual 23,95,200-share public pool by calculation. BSE's separate 7:04:52 p.m. price-demand curve records 3,16,06,800 shares at the ₹87 floor, 38,400 more than the category total; both official views are preserved rather than forced to reconcile. Issue-price, allotment and listing reconciliation remain pending. BSE's 17 August RHP archive is byte-identical to the issuer-hosted final RHP. The issue record also exposes an inaccessible addendum-file path, so no correction is inferred without a readable primary document. The RHP records nil subscription revenue and nil capitalised software assets, while ₹2.60 crore of receivables was older than six months and ₹8.23 crore sat in short-term advances, including ₹5.39 crore to vendors and a ₹2.73 crore inter-corporate deposit. The page also covers the 65-hire plan, disabled accounting audit trail, ₹63.54 lakh TDS balance and unitless 1,519.74 contingent-liability figure. The latest pass adds the one-year limit on IPO-funded salaries and software tools, nil unbilled trade receivables and the 11.05% outside-India revenue share. A capital-allocation and debt review now identifies the ₹6.03 crore Macobs holding, the unsecured ₹2.50 crore ACME facility at 10%, a 79.5%-drawn ₹4.99 crore ICICI line at 9.30% repayable on demand, and the absence of long-term or exclusive customer contracts.",
    "ENS Enterprises' BSE price-demand curve, timestamped 7:04:52 p.m. IST on 18 August, records 3,15,30,000 cumulative shares at the ₹92 cap versus 3,16,06,800 at the ₹87 floor. The derived 99.76% ratio shows limited price drop-off inside the submitted book, but it is not a final issue-price or allotment confirmation.",
    "Fascinate Textiles remained active through the extended 19 August close in NSE's approximately 12:36 a.m. IST 19 August current-issue feed, superseding the RHP's original 13 August close. The feed showed 40,81,600 bids against 42,93,600 displayed gross-offer shares, or 0.95×. Because the denominator includes the 2,15,200-share market-maker reservation, the same demand is approximately 1.00× the residual 40,78,400-share public pool by calculation; neither reading is a final category-wise book. The page records ₹23.99 crore of FY26 related-party sales, equal to 20.5% of revenue, and no doubtful classification despite ₹4.54 crore of receivables over six months. It also shows that ₹23.95 crore, or 49.8%, of inventory was work-in-process, while IPO funding covers only 36.5% of the projected FY27 working-capital requirement and just ₹5 lakh of the new-facility budget had been deployed. The latest debt pass isolates ₹2.36 crore across eight 15.0–18.5% NBFC working-capital loans and shows that the ₹2.68 crore repayment object addresses only 10.3% of FY26 borrowings.",
    "Pramodini Medicare's signed final prospectus dated 17 August fixes the ₹118 offer price and confirms the 58,51,200-share offer, including 53,50,800 fresh shares and a 5,00,400-share promoter OFS. It also confirms the promoter set includes Chalasani Lalithakumari alongside Dr Chalasani Kuldeep Kumar, Dr Chalasani Kavitha, Chalasani Durga Aashritha and Sri Ram Medicare. NSE's official past-issues table confirms the ₹118 issue price and 19 August listing date; at the approximately 8:10 a.m. IST pre-market freeze, no first trade was available. The network reached 16 centres across 14 cities, 100% of the ₹45.15 crore offer-funded equipment remained unordered, and FY26 contingent guarantees included ₹4.95 crore for group companies plus ₹0.67 crore of bank guarantees. The audited-table pass corrects ₹44.21 crore to the year-end PPE and intangible net block rather than equipment additions: FY26 cash purchases were ₹29.81 crore. It also adds ₹5.93 crore of receivables older than six months with no doubtful classification, WDV depreciation over a 13-year medical-equipment life and five professional-indemnity policies totaling ₹90 crore.",
    "ENS Enterprises' final RHP confirms a ₹87–₹92 book-built issue, a 2,400-share minimum bid and proposed 21 August trading; the earlier ₹92 fixed-price label was corrected.",
    "Credent Connect N Care's 8 August RHP confirms 49,68,000 fresh shares, including a 2,52,000-share market-maker reservation. The full offer at the cap is approximately ₹93.90 crore; the RHP directs ₹63.80 crore to parent and subsidiary working capital, while their combined gap is projected to rise from ₹51.89 crore at FY26 to ₹124.65 crore by FY28. NSE's scheduled-close reading remained at 50,74,31,400 bids against the 35,64,000-share post-anchor public pool, or 142.38×, at 8:59 p.m. IST on 17 August. NSE's 18 August past-issues table records the closed issue, but still showed dashes for final issue price and listing date at the approximately 11:40 p.m. IST recheck, so reconciliation and category-wise demand remain pending. The two-lot minimum requires ₹2,26,800 at the cap. The page adds nil bad-debt provision across ₹58.83 crore of receivables, the FY25 adoption and historical restatement of unbilled-revenue accounting, ₹10.91 crore of recallable unsecured loans equal to 47.42% of 30 June indebtedness, and lender security extending to receivables, promoter guarantees and residential collateral. The operating pass now separates a 2,589-rider field network from the 97 owned vehicles, two warehouses and four branch offices so fleet ownership is not mistaken for total delivery capacity.",
    "Lalithaa Jewellery Mart's final RHP and price advertisement confirm a ₹1,200 crore fresh issue, ₹500 crore OFS, ₹190–₹201 band and 74-share lot. BSE's 14 August notice confirms a ₹508.20 crore anchor allocation at ₹201; NSE and BSE show 6,27,61,403 shares in the post-anchor public bid pool. BSE's official book timestamped 12:36:25 a.m. IST on 19 August showed 5,36,03,232 bids, or 0.8541×, with category readings of 1.0108× QIB, 1.1451× NII, 0.6415× retail and 0.7055× employee. NSE's current-issue endpoint separately displayed 14,04,15,518 bids, or 2.2373×, at the same midnight checkpoint. The page keeps the exchange views separate rather than adding them because their aggregation basis is not confirmed; bidding continues through 19 August and both readings remain preliminary. FY26 inventory was 89.7% of assets, while the JILABA sales-and-inventory audit trail did not operate throughout FY26. The page maps ₹8,683.03 crore of gold inventory carried at annual weighted-average cost subject to a net-realizable-value floor, shows customer-scheme advances rising 159.5% since FY24 to ₹5,042.75 crore and separates ₹441.26 crore of lease liabilities from the reported borrowing figure. The latest review adds the 11-month scheme terms and the bonus or value-addition discounts that make customer advances a timed fulfilment and margin obligation rather than free funding.",
    "Milky Mist Dairy Food's final prospectus dated 13 August fixes the offer price at ₹140 and confirms a ₹1,428 crore fresh issue plus ₹125 crore promoter OFS. BSE notice 20260817-39 confirms B-group trading from 18 August, with 14 August allotment, 76,98,43,411 post-issue shares, scrip 544868 / MILKYMIST, ISIN INE00IT01020 and a one-share secondary-market lot. BSE's official 4:00 p.m. quote header records a ₹165 open and low and a ₹181.45 high and end-of-session value, 29.61% above the ₹140 issue price. Its analysis includes FY26 milk sourcing, the 59.05% paneer-cheese-curd revenue share, 48 working-capital days, ₹229.01 crore of contingent liabilities, partial capex ordering and the offer document's PPE, inventory and internal-audit observations.",
    "Shiprocket's final prospectus dated 14 August fixes the offer price at ₹97, confirms a ₹885.50 crore fresh issue plus ₹731.98 crore OFS and corrects the face value to ₹10. BSE notice 20260818-36 records 17 August allotment and confirms B-group listing from 19 August through a special pre-open session under scrip 544871 / SHIPROCKET, ISIN INE0FOO01011, with 72,75,77,587 post-issue shares and a one-share lot. No first trade was available at the approximately 8:10 a.m. IST pre-market freeze. Its page separates statutory from adjusted EBITDA and adds active merchants, transactions, power-merchant ARPU, 84.50% top-five courier concentration, historical acquisition impairments and FY26 audit-trail observations.",
    "Behari Lal Engineering's final RHP confirms a ₹93 crore fresh issue allocating ₹63.04 crore to equipment and solar, ₹0.57 crore to debt repayment and the balance to general purposes. BSE notice 20260818-37 records 17 August allotment and confirms B-group listing from 19 August through a special pre-open session under scrip 544870 / BLEL, ISIN INE1EEM01017, at the ₹285 issue price with 4,23,02,482 post-issue shares and a one-share lot. No first trade was available at the approximately 8:10 a.m. IST pre-market freeze. FY26 revenue, EBITDA and PAT were ₹534.03 crore, ₹101.33 crore and ₹64.64 crore, but operating cash flow was only ₹27.54 crore and working-capital days rose to 132; inventory days rose to 57 from 34 in FY24, top-ten suppliers represented 38.39% of expenses, contingent liabilities were ₹3.56 crore and the entire expansion budget was undeployed at the RHP date.",
    "Horizon Industrial Parks' final RHP and price advertisement confirm an all-fresh ₹2,600 crore issue, ₹57–₹60 band, 250-share lot and ₹2,250 crore debt-repayment object. BSE's 14 August notice confirms a ₹1,167.75 crore anchor allocation at ₹60; NSE and BSE show a 25,13,56,273-share post-anchor public pool. BSE's official book timestamped 12:36:25 a.m. IST on 19 August showed 3,05,43,500 bids, or 0.1215×, with category readings of 0.1771× QIB, 0.0161× NII, 0.1125× retail and 0.1427× employee. NSE's current-issue endpoint separately displayed 2,91,02,500 bids, or 0.1158×, at the same midnight checkpoint. Because the two official exchange views use separately maintained feeds, they are not combined or treated as a single time series; bidding continues through 19 August and both readings remain preliminary. Post-repayment net external debt remains about 3.28× FY26 EBITDA. The page separates five- to 10-year lease terms from one- to five-year lock-ins, maps the ₹0.90 crore lifetime loss allowance against ₹35.79 crore of gross receivables and records 1.16× pre-issue DSCR, 1.36× interest-service cover and ₹77.94 crore of recallable subsidiary debt. The latest debt-use pass shows that the object addresses only 32.68% of FY26 borrowings and that some subsidiary facilities may attract prepayment or break costs up to 1%.",
    "Shankesh Jewellers' 10 August RHP and official 11 August price-band advertisement confirm 2,94,82,000 fresh shares, 1,00,00,000 OFS shares, a ₹88–₹93 band, 160-share lot and 18–20 August bidding. BSE notice 20260817-31 adds the final 1,18,44,600-share anchor allocation at ₹93, while issue record 7889 now agrees with the official 160-share lot. The receivable schedule separates ₹126.42 crore of net receivables, virtually all under six months, from a ₹0.64 crore credit-impaired balance that is fully provided.",
    "Sunshine Pictures' final RHP, official price advertisement and BSE issue record 7892 confirm 48,00,034 fresh shares, 30,37,157 OFS shares, a ₹342–₹360 band and 41-share lot. BSE notice 20260817-32 adds the final 23,51,140-share anchor allocation at ₹360, worth approximately ₹84.64 crore; NSE and BSE display 54,86,051 shares in the post-anchor public pool. BSE's official 5:00 p.m. IST day-one category book showed 63,10,392 bids, or 1.1503×, with QIB 0.0206×, NII 1.9540× and retail 1.4513×. NSE's current-issue endpoint separately still displayed 1,74,64,319 bids, or 3.1834×, at the approximately 8:04 p.m. recheck; the exchange views are not combined. BSE issue record 7892 contained no addendum or corrigendum at the recheck. The page shows trade receivables increasing 8.35× since FY24 to ₹66.51 crore with no loss allowance, and explains that content-cost amortisation depends on expected unrealised revenue as a share of total expected revenue. An immediate write-down occurs only when net expected unrealised revenue falls below unamortised cost. The issuer also states a 30% annual-budget limit per project, but own productions bear all overruns and title-level compliance is not disclosed.",
    "Q&T Foods' final prospectus corrects the issue size to ₹26.2476 crore, confirms ₹22.59 crore estimated net proceeds and a 2,400-share minimum application. BSE's 14 August 5:36:15 p.m. close book records 31,99,200 bids, equal by calculation to 1.40× the gross offer or 1.48× the net issue; because BSE left the category offered-share fields blank, no category subscription multiple is stated. BSE notice 20260818-34 confirms 17 August allotment and MT-group listing from 19 August at ₹115 under scrip 544872 / QTFOODS, with a 1,200-share trading lot and 70,77,200 post-allotment shares. That final exchange count corrects the earlier 70,78,400-share prospectus-based valuation denominator. No first trade was available at the approximately 8:10 a.m. IST pre-market freeze. Receivables and inventory represented 87.64% of FY26 current assets, inventory had risen 114.7% since FY24 and the prospectus attributes the build to raw material not fully consumed in production. The debt pass adds the ₹9.50 crore draw against an ₹11.00 crore SBI cash-credit line at 8.40%, the 2% repayment or takeover charge, security over current assets, three properties and four personal guarantees, and an interest-free ₹0.15 crore promoter-director demand loan. The analysis also retains 91.33% FY26 utilisation, the roughly 101-day cash cycle, dealer-credit, FEFO, statutory-payment, litigation and FSSAI controls.",
    "LAPL Automotive's BSE notices confirm a 9,76,800-share anchor allocation at ₹94, 1,25,36,218 post-issue shares, ₹94 final price and listing from 13 August under scrip 544863. Its page now distinguishes the ₹32.40 crore gross offer, post-anchor pool, 2,400-share minimum bid and 1,200-share trading lot.",
    "Optimystix Entertainment's final RHP confirms 50,00,000 fresh shares, 12,00,000 OFS shares and a 1,600-share minimum bid; NSE's 14 August bhavdata confirms first trading under OPTIMYSTIX, opening at ₹180 and closing at ₹189. Its page now uses audited FY24–FY26 statements and highlights negative FY26 operating cash flow.",
    "Sham Foam's 10 August final prospectus and BSE issue record 7881 confirm a 31,14,000-share fresh issue at ₹130, including a 1,56,000-share market-maker reservation and a 2,000-share minimum application. BSE's close book records 72,47,000 bids, equal by calculation to 2.33× the gross offer or 2.45× the net issue; category multiples remain unavailable because BSE left the offered-share fields blank. BSE notice 20260817-50 confirms 18 August MT-group listing, 14 August allotment, 1,14,90,750 post-issue shares, scrip 544869 / SHAMFOAM, ISIN INE0Z9N01013 and a 1,000-share trading lot, with the scrip in trade-for-trade for 10 trading days. BSE's 4:00 p.m. quote header records a ₹104 open, ₹109 high and ₹98.80 low and end-of-session value, 24.00% below the issue price. The page also shows ₹25.40 crore of receivables, a 93-day collection cycle, ₹9.50 crore of inventory and ₹3.52 crore of unsecured demand loans alongside the unordered ₹14.72 crore capex programme.",
    "Fascinate Textiles' RHP confirms 34,57,600 fresh shares, an 8,36,000-share OFS and a 1,600-share minimum bid; the calendar now shows the approximately ₹66.98 crore full offer at the cap rather than a floor-price estimate.",
    "Skytech Infinite Platform's final RHP confirms 29,45,600 fresh shares, including a 1,48,800-share market-maker reservation, and the lead manager's price advertisement confirms ₹77.",
    "At the approximately 6:42 a.m. IST pre-session recheck on 19 August, BSE showed Lalithaa at 5,36,32,906 bids or 0.8546×, Horizon at 3,05,45,750 bids or 0.1215×, Shankesh at 35,14,560 bids or 0.1272× and Sunshine at 66,38,187 bids or 1.2100×. NSE remained at 2.2373×, 0.1158×, 0.2342× and 3.1834× for the same four issues, respectively; Fascinate remained at 0.95× and Gaja still showed zero bids before market open. These are explicitly opening carry-forward states, not final-day demand, and the exchange views are not added together.",
  ],
  sourceLinks: [
    { label: "Chittorgarh Mainboard IPO Calendar", href: "https://www.chittorgarh.com/calendar/ipo-calendar/1/?month=8&year=2026" },
    { label: "Chittorgarh SME IPO Calendar", href: "https://www.chittorgarh.com/calendar/sme-ipo-calendar/2/?month=8&year=2026" },
    { label: "NSE Issue Information", href: "https://www.nseindia.com/market-data/all-upcoming-issues-ipo" },
    { label: "BSE Public Issue Information", href: "https://www.bseindia.com/markets/PublicIssues/IPOIssues_new.aspx" },
  ],
};
