import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Landmark } from "lucide-react";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { FAQSection, type FAQ } from "@/components/seo/FAQSection";
import { JsonLd } from "@/components/seo/JsonLd";
import { NpsAnnuityCalculator } from "./NpsAnnuityCalculator";

const canonicalUrl = "https://www.sohowealth.in/tools/nps-annuity-calculator";
const socialImage = "https://www.sohowealth.in/retirement-planning/opengraph-image";
export const metadata: Metadata = { title: "NPS Annuity Calculator India | Monthly Pension", description: "Calculate gross monthly, quarterly and annual NPS annuity income using your corpus, annuity share and live quoted rate. Compare like-for-like options.", keywords: ["NPS annuity calculator", "NPS pension calculator India", "NPS monthly pension calculator", "annuity payout calculator India"], alternates: { canonical: canonicalUrl }, robots: { index: true, follow: true }, openGraph: { title: "NPS Annuity Calculator India", description: "Estimate annuity income from an NPS corpus using a live provider quote.", url: canonicalUrl, type: "website", images: [socialImage] }, twitter: { card: "summary_large_image", title: "NPS Annuity Calculator India", description: "Estimate monthly, quarterly and annual annuity payout from an entered live quote.", images: [socialImage] } };
const faqs: FAQ[] = [
  { q: "How does the NPS annuity calculator work?", a: "It multiplies the annuity purchase amount by the annual rate you enter, then divides the gross payout into annual, quarterly and monthly illustrations." },
  { q: "Does this calculator show live NPS annuity rates?", a: "No. Rates change by provider, age, option, frequency and market conditions. Enter a current like-for-like quote from an empanelled provider." },
  { q: "Is the highest annuity rate always best?", a: "No. A higher initial payout may provide different spouse, estate or purchase-price benefits. Compare the contract promise as well as the rate." },
  { q: "Is the calculated annuity tax-free?", a: "Do not assume that. The result is gross and does not model tax. Confirm current treatment for your circumstances with a qualified tax professional." },
];
const schema = { "@context": "https://schema.org", "@type": "WebApplication", name: "NPS Annuity Calculator India", url: canonicalUrl, applicationCategory: "FinanceApplication", operatingSystem: "Any", isAccessibleForFree: true, description: "A browser-based calculator for gross NPS annuity payout using an entered live quote.", featureList: ["Monthly annuity estimate", "Quarterly and annual payout", "Editable annuity allocation", "No personal data required"], citation: ["https://npstrust.org.in/normal-exit", "https://npstrust.org.in/index.php/list-of-annuity-service-provider-enrolled-under-nps"], offers: { "@type": "Offer", price: 0, priceCurrency: "INR" }, provider: { "@id": "https://www.sohowealth.in/#organization" } };
export default function NpsAnnuityCalculatorPage() { return <main className="bg-white pt-20"><JsonLd data={schema} /><Breadcrumbs items={[{ name: "Retirement Planning", href: "/retirement-planning" }, { name: "NPS Annuity Calculator", href: "/tools/nps-annuity-calculator" }]} /><section className="bg-[#07192F] py-16 text-white lg:py-24"><div className="container mx-auto max-w-5xl px-6 text-center lg:px-8"><span className="inline-flex items-center gap-2 rounded-full border border-[#C9A84C]/40 bg-[#C9A84C]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.15em] text-[#E5CB83]"><Landmark className="h-4 w-4" /> Free NPS planning tool</span><h1 className="mx-auto mt-6 max-w-4xl font-display text-4xl font-semibold md:text-6xl">NPS annuity calculator for India.</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-white/70">Turn a live annuity quote into comparable monthly, quarterly and annual income—without mistaking the quote for an investment return.</p></div></section><NpsAnnuityCalculator /><section className="bg-white py-16"><div className="container mx-auto max-w-4xl px-6 lg:px-8"><h2 className="font-display text-3xl font-semibold text-[#0B1F3A]">Compare the promise behind the rate</h2><p className="mt-4 leading-relaxed text-slate-600">Use identical purchase amount, age, payout frequency and annuity option when comparing providers. Then review spouse continuation, return of purchase price, liquidity, inflation and current tax treatment.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/insights/nps-annuity-rates-retirement-decision" className="inline-flex items-center justify-center rounded-xl bg-[#0B1F3A] px-6 py-3 text-sm font-bold text-white">Read the annuity decision guide <ArrowRight className="ml-2 h-4 w-4" /></Link><Link href="/insights/nps-lump-sum-vs-annuity" className="inline-flex items-center justify-center rounded-xl border border-slate-300 px-6 py-3 text-sm font-bold text-[#0B1F3A]">Compare NPS exit choices</Link></div></div></section><FAQSection faqs={faqs} heading="NPS Annuity Calculator FAQs" background="#F7F8FA" /></main>; }
