import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, WalletCards } from "lucide-react";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { FAQSection, type FAQ } from "@/components/seo/FAQSection";
import { JsonLd } from "@/components/seo/JsonLd";
import { RetirementIncomeCalculator } from "./RetirementIncomeCalculator";

const canonicalUrl = "https://www.sohowealth.in/tools/retirement-income-calculator";
export const metadata: Metadata = { title: "Retirement Income Calculator India | Monthly Income", description: "Estimate inflation-adjusted monthly income from an existing retirement corpus using editable return, inflation, pension and retirement-duration assumptions.", keywords: ["retirement income calculator India", "monthly income from retirement corpus", "retirement withdrawal calculator India", "retirement corpus income"], alternates: { canonical: canonicalUrl }, robots: { index: true, follow: true }, openGraph: { title: "Retirement Income Calculator India", description: "Estimate first-year monthly income from your retirement corpus and pension.", url: canonicalUrl, type: "website", images: ["https://www.sohowealth.in/retirement-planning/opengraph-image"] }, twitter: { card: "summary_large_image", title: "Retirement Income Calculator India", description: "Estimate inflation-adjusted monthly income from a retirement corpus and pension.", images: ["https://www.sohowealth.in/retirement-planning/opengraph-image"] } };
const faqs: FAQ[] = [
  { q: "How is monthly retirement income calculated?", a: "The tool converts expected return and inflation into an approximate real return, then models level purchasing-power withdrawals over the selected period. It adds other fixed monthly income separately." },
  { q: "Does this calculator guarantee the corpus will last?", a: "No. Real returns are uneven, while tax, fees, emergencies, longevity and withdrawal timing can materially change the outcome." },
  { q: "Should healthcare reserves be included in the corpus?", a: "Only include money available for regular income. Keep separately earmarked healthcare, emergency and near-term goal reserves outside the input to avoid double use." },
  { q: "Are my values stored?", a: "No. The calculator runs in your browser and does not ask for personal identifiers or account details." },
];
const schema = { "@context": "https://schema.org", "@type": "WebApplication", name: "Retirement Income Calculator India", url: canonicalUrl, applicationCategory: "FinanceApplication", operatingSystem: "Any", isAccessibleForFree: true, description: "A browser-based calculator estimating inflation-adjusted monthly income from a retirement corpus.", featureList: ["Monthly corpus withdrawal estimate", "Pension-inclusive income", "Real return calculation", "Editable income-period assumptions"], citation: ["https://investor.sebi.gov.in/moneymatters-planforearlyretire.html", "https://investor.sebi.gov.in/calculators/Assets_Allocations.html"], offers: { "@type": "Offer", price: 0, priceCurrency: "INR" }, provider: { "@id": "https://www.sohowealth.in/#organization" } };

export default function RetirementIncomeCalculatorPage() { return <main className="bg-white pt-20"><JsonLd data={schema} /><Breadcrumbs items={[{ name: "Retirement Planning", href: "/retirement-planning" }, { name: "Income Calculator", href: "/tools/retirement-income-calculator" }]} /><section className="bg-[#07192F] py-16 text-white lg:py-24"><div className="container mx-auto max-w-5xl px-6 text-center lg:px-8"><span className="inline-flex items-center gap-2 rounded-full border border-[#C9A84C]/40 bg-[#C9A84C]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.15em] text-[#E5CB83]"><WalletCards className="h-4 w-4" /> Free planning tool</span><h1 className="mx-auto mt-6 max-w-4xl font-display text-4xl font-semibold md:text-6xl">Retirement income calculator for India.</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-white/70">Estimate the first-year monthly income an existing corpus may support after accounting for inflation and your chosen income period.</p></div></section><RetirementIncomeCalculator />
<section className="border-y border-slate-200 bg-[#F7F8FA] py-16" aria-labelledby="income-method-heading"><div className="container mx-auto max-w-5xl px-6 lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#9A761F]">Calculation methodology</p><h2 id="income-method-heading" className="mt-3 font-display text-3xl font-semibold text-[#0B1F3A]">How the retirement-income estimate works</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{[
  ["1. Find the real return", "The calculator adjusts the expected nominal return for inflation using (1 + return) ÷ (1 + inflation) − 1."],
  ["2. Spread income across time", "It uses that real return to estimate a level purchasing-power withdrawal over the selected number of years."],
  ["3. Add other fixed income", "Pension or other fixed monthly income is shown separately and added after the portfolio withdrawal is calculated."],
].map(([title, text]) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-display text-xl font-semibold text-[#0B1F3A]">{title}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">{text}</p></article>)}</div><p className="mt-7 text-sm leading-relaxed text-slate-600">This is a smooth-return illustration, not a safe-withdrawal guarantee. Actual portfolios experience uneven returns, taxes, fees and unexpected spending. A poor market sequence early in retirement can produce a different outcome even when the long-term average return is the same.</p></div></section>
<section className="bg-white py-16"><div className="container mx-auto max-w-4xl px-6 lg:px-8"><h2 className="font-display text-3xl font-semibold text-[#0B1F3A]">Use a range, not one perfect answer</h2><p className="mt-4 leading-relaxed text-slate-600">Test lower returns, higher inflation and a longer retirement. Then compare the result with essential expenses, healthcare reserves and income that continues for your spouse.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/insights/safe-withdrawal-rate-india-retirement" className="inline-flex items-center justify-center rounded-xl bg-[#0B1F3A] px-6 py-3 text-sm font-bold text-white">Understand withdrawal rates <ArrowRight className="ml-2 h-4 w-4" /></Link><Link href="/retirement-planning" className="inline-flex items-center justify-center rounded-xl border border-slate-300 px-6 py-3 text-sm font-bold text-[#0B1F3A]">Explore retirement planning</Link></div></div></section><FAQSection faqs={faqs} heading="Retirement Income Calculator FAQs" background="#F7F8FA" /></main>; }
