import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Calculator, LockKeyhole } from "lucide-react";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { FAQSection, type FAQ } from "@/components/seo/FAQSection";
import { JsonLd } from "@/components/seo/JsonLd";
import { RetirementCalculator } from "./RetirementCalculator";

const canonicalUrl = "https://www.sohowealth.in/tools/retirement-calculator";
export const metadata: Metadata = { title: "Retirement Calculator India: Corpus & SIP | SoHo", description: "Calculate an illustrative retirement corpus, future monthly expenses, corpus gap and required monthly investment using editable Indian retirement assumptions.", keywords: ["retirement calculator India", "retirement corpus calculator", "retirement SIP calculator", "how much money to retire in India"], alternates: { canonical: canonicalUrl }, openGraph: { title: "Retirement Corpus Calculator India", description: "Estimate retirement expenses, corpus and monthly investment privately in your browser.", url: canonicalUrl, type: "website" } };
const faqs: FAQ[] = [
  { q: "How does the retirement calculator estimate the corpus?", a: "It inflates today's expenses to retirement, subtracts the entered pension, and calculates the present value at retirement of increasing annual withdrawals over the selected retirement period. It then adds the separate healthcare reserve." },
  { q: "What return should I assume after retirement?", a: "Use an expected post-tax portfolio return, not the return of the best-performing product. Test a lower-return case because actual returns will be uneven and uncertain." },
  { q: "Does the calculator include NPS and EPF?", a: "Include the current value of goal-linked NPS, EPF and other retirement assets in current corpus. Enter a pension only if it will be a separate monthly income; do not count the same asset twice." },
  { q: "Are my values saved?", a: "No. Calculations run locally in your browser and the page does not require personal identifiers or account information." },
];
const schema = { "@context": "https://schema.org", "@type": "WebApplication", name: "SoHo Wealth Retirement Corpus Calculator", url: canonicalUrl, applicationCategory: "FinanceApplication", operatingSystem: "Any", isAccessibleForFree: true, description: "Browser-based retirement corpus and monthly investment calculator for India.", provider: { "@id": "https://www.sohowealth.in/#organization" } };
export default function RetirementCalculatorPage() { return <main className="bg-white pt-20"><JsonLd data={schema} id="retirement-calculator-schema" /><Breadcrumbs items={[{ name: "Retirement Planning", href: "/retirement-planning" }, { name: "Retirement Calculator", href: "/tools/retirement-calculator" }]} /><section className="relative overflow-hidden bg-[#07192F] py-16 text-white lg:py-24"><div className="container mx-auto max-w-5xl px-6 text-center lg:px-8"><span className="inline-flex items-center gap-2 rounded-full border border-[#C9A84C]/40 bg-[#C9A84C]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.15em] text-[#E5CB83]"><Calculator className="h-4 w-4" /> Free retirement planning tool</span><h1 className="mx-auto mt-6 max-w-4xl font-display text-4xl font-semibold md:text-6xl">Retirement corpus calculator for India.</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-white/70">Estimate future expenses, the corpus required, your funding gap and an indicative monthly investment—with assumptions you can see and change.</p><p className="mt-7 inline-flex items-center gap-2 text-sm text-white/55"><LockKeyhole className="h-4 w-4 text-[#C9A84C]" /> Your inputs stay in your browser</p></div></section><RetirementCalculator /><section className="bg-white py-16"><div className="container mx-auto max-w-4xl px-6 lg:px-8"><h2 className="font-display text-3xl font-semibold text-[#0B1F3A]">Use three scenarios, not one answer</h2><div className="mt-7 grid gap-5 md:grid-cols-3">{[["Base case", "Reasonable spending, longevity and post-tax return assumptions."], ["Stress case", "Higher inflation, lower returns and a longer life."], ["Action case", "A contribution and retirement date you can actually maintain."]].map(([t,c]) => <div key={t} className="rounded-2xl border border-slate-200 p-6"><h3 className="font-display text-xl font-semibold text-[#0B1F3A]">{t}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">{c}</p></div>)}</div><Link href="/retirement-planning" className="mt-9 inline-flex items-center font-bold text-[#0B1F3A]">Explore the complete retirement planning service <ArrowRight className="ml-2 h-4 w-4" /></Link></div></section><FAQSection faqs={faqs} heading="Retirement Calculator FAQs" background="#F7F8FA" /></main>; }
