import type { Metadata } from "next";
import { ClipboardCheck } from "lucide-react";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { FAQSection, type FAQ } from "@/components/seo/FAQSection";
import { JsonLd } from "@/components/seo/JsonLd";
import { RetirementReadinessCheck } from "./RetirementReadinessCheck";

const canonicalUrl = "https://www.sohowealth.in/tools/retirement-readiness-check";
export const metadata: Metadata = { title: "Retirement Readiness Check India | SoHo Wealth", description: "Check retirement-planning readiness across corpus, income, healthcare, debt, liquidity, spouse continuity, NPS and documentation.",  alternates: { canonical: canonicalUrl }, robots: { index: true, follow: true }, openGraph: { title: "Retirement Readiness Check India", description: "A private 10-point check of retirement-planning foundations.", url: canonicalUrl, type: "website", images: ["https://www.sohowealth.in/retirement-planning/opengraph-image"] }, twitter: { card: "summary_large_image", title: "Retirement Readiness Check India", description: "Check ten retirement-planning foundations and identify the next gap to resolve.", images: ["https://www.sohowealth.in/retirement-planning/opengraph-image"] } };
const faqs: FAQ[] = [
  { q: "What does the retirement readiness score measure?", a: "It measures whether ten planning foundations are marked complete. It does not predict returns, recommend investments or guarantee retirement success." },
  { q: "What is a good retirement readiness score?", a: "The score is a prompt, not an industry benchmark. More important than the number is identifying the first incomplete area and resolving it with real calculations or documents." },
  { q: "Does SoHo Wealth store my answers?", a: "No. The selections remain in your browser and no personal account information is requested." },
];
const schema = { "@context": "https://schema.org", "@type": "WebApplication", name: "Retirement Readiness Check India", url: canonicalUrl, applicationCategory: "FinanceApplication", operatingSystem: "Any", isAccessibleForFree: true, description: "A private ten-point check of retirement income, corpus, healthcare, liquidity, debt and family continuity.", featureList: ["Ten-point retirement checklist", "Instant readiness score", "Personalised next-step guide", "No personal data required"], citation: ["https://investor.sebi.gov.in/moneymatters-planforearlyretire.html", "https://investor.sebi.gov.in/calculators/financial_goal_planner.html"], offers: { "@type": "Offer", price: 0, priceCurrency: "INR" }, provider: { "@id": "https://www.sohowealth.in/#organization" } };
export default function RetirementReadinessPage() { return <main className="bg-white pt-20"><JsonLd data={schema} /><Breadcrumbs items={[{ name: "Retirement Planning", href: "/retirement-planning" }, { name: "Readiness Check", href: "/tools/retirement-readiness-check" }]} /><section className="bg-[#07192F] py-16 text-white lg:py-24"><div className="container mx-auto max-w-5xl px-6 text-center lg:px-8"><span className="inline-flex items-center gap-2 rounded-full border border-[#C9A84C]/40 bg-[#C9A84C]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.15em] text-[#E5CB83]"><ClipboardCheck className="h-4 w-4" /> Private 10-point check</span><h1 className="mx-auto mt-6 max-w-4xl font-display text-4xl font-semibold md:text-6xl">Are your retirement foundations ready?</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-white/70">Check the plan across income, corpus, liquidity, healthcare, debt, spouse continuity and family documentation—then see the most useful next step.</p></div></section><RetirementReadinessCheck /><FAQSection faqs={faqs} heading="Retirement Readiness Check FAQs" background="#FFFFFF" /></main>; }
