import type { LandingPageConfig } from "./LandingPageClient";

export const wealthManagementHyderabad: LandingPageConfig = {
  slug: "wealth-management-hyderabad",
  title: "Wealth Planning in Hyderabad",
  eyebrow: "Hyderabad wealth-planning process",
  h1: "Wealth Planning and Investment Distribution for",
  highlightedH1: "HNIs, Founders, Families & NRIs.",
  intro: "SoHo Wealth is a Hyderabad-based portfolio-review and investment-distribution firm. This page explains our process, registrations, product scope, office access and ongoing service for investors who want their holdings organised under one relationship.",
  primaryCta: "Book a Hyderabad Consultation",
  secondaryCta: "WhatsApp SoHo Wealth",
  serviceName: "Wealth Planning and Investment Distribution in Hyderabad",
  serviceDescription: "Portfolio review, wealth planning and investment distribution in Hyderabad for HNIs, NRIs, families, founders and professionals.",
  serviceType: "Investment Distribution and Portfolio Review",
  leadSource: "wealth-management-hyderabad page",
  formHeading: "Book a Wealth Management Consultation",
  formTitle: "Get a Clear View of Your Wealth",
  formCopy: "Bring your portfolio, goals and questions. We will help you identify gaps, risks, fees and the right next step.",
  formBullets: [
    "Portfolio health check",
    "Asset allocation and risk review",
    "PMS, SIF, AIF and mutual fund structure comparison",
    "NRI and global-investing coordination questions",
    "Direct consultation with Kiran Dutta",
  ],
  sections: [
    {
      eyebrow: "Why SoHo Wealth",
      heading: "A Clear, Local Wealth-Planning Process",
      copy: "The engagement begins with what you already own, what each goal needs, and which risks, costs or liquidity constraints deserve attention. Product implementation follows only after the portfolio context is clear.",
      cards: [
        { title: "Multi-Provider Product Shelf", description: "SoHo Wealth is not tied to one AMC or PMS provider. Options are compared within our disclosed distribution scope." },
        { title: "Hyderabad-First, India-Wide", description: "Meet in person in Hyderabad or work with us remotely across India and overseas as an NRI." },
        { title: "Connected Portfolio View", description: "Mutual funds, PMS, SIF, AIF, pre-IPO and global holdings are discussed as one balance sheet." },
        { title: "Portfolio Review First", description: "Before any product conversation, we look at existing holdings, concentration, costs, liquidity and goal alignment." },
        { title: "Transparent Follow-Through", description: "You get ongoing monitoring, reviews and simple explanations instead of one-time product placement." },
        { title: "Registered Distribution", description: "AMFI mutual fund and SIF distributor ARN 306593; APMI PMS distributor APRN01233. SoHo Wealth is not a SEBI RIA." },
      ],
    },
    {
      eyebrow: "Khajaguda office or video",
      heading: "What Happens in a Hyderabad Portfolio Review",
      copy: "The first meeting is a fact-finding and organisation session. Bring a consolidated account statement, demat and PMS summaries, insurance list, liabilities, major goals and—where relevant—RSU or business-ownership details.",
      cards: [
        { title: "Before the Meeting", description: "Share only the broad documents you are comfortable sharing. Remove passwords and unnecessary identity data." },
        { title: "During the Review", description: "We map ownership, goal horizon, liquidity, concentration, product costs and questions that need another specialist." },
        { title: "After the Review", description: "You receive a prioritised discussion of what to retain, investigate or compare; no transaction is required." },
        { title: "In-Person Access", description: "Meet at 110, Green Grace, Khajaguda, Hyderabad, by appointment from Monday to Saturday." },
        { title: "Remote Access", description: "Video reviews are available across India and for overseas families who need a Hyderabad relationship point." },
        { title: "Ongoing Service", description: "Where products are implemented through SoHo Wealth, provider documents, transactions and periodic portfolio service are coordinated." },
      ],
    },
    {
      eyebrow: "Role and compensation",
      heading: "Know Which Hat SoHo Wealth Is Wearing",
      copy: "SoHo Wealth is an AMFI mutual fund and SIF distributor (ARN 306593) and an APMI PMS distributor (APRN01233), not a SEBI Registered Investment Adviser. Distribution compensation can come from product providers and is described in applicable documents and disclosures.",
      bullets: [
        "Regular-plan mutual funds can pay trail commission to the distributor",
        "PMS and SIF distribution compensation depends on provider arrangements and documents",
        "Tax returns, legal opinions and security-level recommendations are outside our scope",
        "A consultation does not require you to transact or transfer existing holdings",
        "Product risk, liquidity, costs and official documents should be read before investing",
      ],
    },
  ],
  comparison: {
    heading: "Service Scope at a Glance",
    columns: [
      { key: "soho", label: "SoHo Wealth" },
      { key: "specialist", label: "Outside Specialist" },
    ],
    highlightKey: "soho",
    rows: [
      { feature: "Portfolio inventory and goal map", soho: "Included in the review process", specialist: "Not usually required" },
      { feature: "Mutual fund, SIF and PMS distribution", soho: "Within disclosed registrations", specialist: "Product provider or platform" },
      { feature: "Income-tax return and opinion", soho: "Question coordination only", specialist: "Chartered accountant or tax counsel" },
      { feature: "Will, title and legal documents", soho: "Question coordination only", specialist: "Qualified lawyer" },
      { feature: "Insurance recommendation and policy advice", soho: "Portfolio inventory and referral", specialist: "Licensed insurance professional" },
    ],
  },
  faqs: [
    { q: "Who is a good fit for SoHo Wealth in Hyderabad?", a: "SoHo Wealth is suited to HNIs, families, founders, senior professionals, tech employees and NRIs who want a structured portfolio review and registered distribution support across mutual funds, PMS, SIF and related eligible products." },
    { q: "Is the first consultation free?", a: "Yes. The first portfolio review or consultation is complimentary and no-obligation. It is meant to help you understand your current portfolio and possible next steps." },
    { q: "Do you work only with Hyderabad clients?", a: "No. SoHo Wealth is based in Hyderabad but works with clients across India and NRIs globally through video consultations." },
    { q: "What is the minimum portfolio size?", a: "The complimentary review is most useful for investors with Rs. 25 lakh or more in investable assets. Product minimums differ: SIF starts at Rs. 10 lakh, PMS at Rs. 50 lakh and AIF at Rs. 1 crore." },
    { q: "Is SoHo Wealth a SEBI Registered Investment Adviser?", a: "No. SoHo Wealth is an AMFI-registered mutual fund and SIF distributor (ARN 306593) and an APMI-registered PMS distributor (APRN01233). Its role is portfolio review, wealth planning and investment distribution; tax, legal and security-specific advice should be confirmed with qualified specialists." },
  ],
  related: [
    { title: "PMS Advisory", href: "/pms-advisory", description: "Compare concentrated listed-equity PMS strategies from Rs. 50 lakh." },
    { title: "SIF Advisory", href: "/sif", description: "Explore SEBI-regulated SIFs from Rs. 10 lakh." },
    { title: "Free Portfolio Review", href: "/portfolio-review", description: "Get a 30-minute review of your current investments." },
  ],
};

export const bestPmsHyderabad: LandingPageConfig = {
  slug: "best-pms-in-hyderabad",
  title: "Best PMS in Hyderabad: Research Guide",
  eyebrow: "Data-led PMS research",
  h1: "Looking for the Best PMS in Hyderabad?",
  highlightedH1: "Start With Evidence, Not a Winner List.",
  intro: "There is no universal best PMS. Use the source-backed tables on this page to discover strategies, then evaluate mandate, drawdowns, manager continuity, fees, churn, tax impact and fit with your existing holdings.",
  primaryCta: "Discuss the Research",
  secondaryCta: "WhatsApp About PMS",
  serviceName: "PMS Research and Comparison in Hyderabad",
  serviceDescription: "Educational PMS research for Hyderabad HNIs comparing published performance, investment approaches, drawdowns, fees and portfolio fit.",
  serviceType: "PMS Research and Educational Comparison",
  leadSource: "best-pms-in-hyderabad page",
  formHeading: "Book a PMS Comparison Call",
  formTitle: "Move From a Leaderboard to a Due-Diligence Shortlist",
  formCopy: "Use the public data as a starting point, then discuss mandate, manager continuity, volatility, fees, documentation and portfolio overlap before committing Rs. 50 lakh or more.",
  formBullets: [
    "PMS suitability check",
    "Manager and strategy comparison",
    "Fee, exit load and tax review",
    "Risk and drawdown discussion",
    "Distributor onboarding support where suitable",
  ],
  sections: [
    {
      eyebrow: "Evaluation Framework",
      heading: "How to Choose a PMS Beyond Past Returns",
      copy: "PMS performance can look attractive in one market cycle and struggle in another. The tables above use a shared as-on period for comparability; they do not predict future returns or constitute a recommendation.",
      cards: [
        { title: "Strategy Style", description: "Large cap, multi cap, small cap, quant, thematic and long-short PMS strategies behave very differently." },
        { title: "Drawdown History", description: "A strategy's worst periods often tell you more about suitability than its best periods." },
        { title: "Portfolio Concentration", description: "Most PMS portfolios hold fewer stocks than mutual funds, which can increase both upside and volatility." },
        { title: "Fund Manager Continuity", description: "Tenure, process discipline and team depth matter when evaluating repeatability." },
        { title: "Fees and Exit Loads", description: "Fixed fees, performance fees, hurdle rates and exit terms can materially affect net returns." },
        { title: "Tax Impact", description: "PMS investors own the underlying securities, so portfolio churn can create investor-level capital gains." },
      ],
    },
    {
      heading: "Who Should Consider PMS?",
      bullets: [
        "Investors with at least Rs. 50 lakh available for one PMS strategy",
        "HNIs who can handle higher volatility than diversified mutual funds",
        "Investors seeking direct stock ownership and a concentrated portfolio",
        "Families looking to complement mutual funds with active manager exposure",
        "NRIs investing through compliant account structures",
      ],
    },
  ],
  comparison: {
    heading: "PMS vs Mutual Funds",
    columns: [
      { key: "mf", label: "Mutual Fund" },
      { key: "pms", label: "PMS" },
    ],
    highlightKey: "pms",
    rows: [
      { feature: "Minimum investment", mf: "Can start from SIP levels", pms: "Rs. 50 lakh minimum" },
      { feature: "Portfolio structure", mf: "Pooled fund units", pms: "Stocks held in investor's demat" },
      { feature: "Concentration", mf: "Usually 40-80 securities", pms: "Often 15-25 securities" },
      { feature: "Tax treatment", mf: "Tax when units are sold", pms: "Capital gains from manager trades" },
      { feature: "Customization", mf: "Limited", pms: "Higher, depending on mandate" },
    ],
  },
  faqs: [
    { q: "What is the minimum amount for PMS in India?", a: "The SEBI-mandated minimum for PMS is Rs. 50 lakh per investor. This applies across PMS providers." },
    { q: "Which PMS is best in Hyderabad?", a: "There is no single best PMS for every investor. Rankings change with the period selected, while suitability depends on mandate, risk, time horizon, existing holdings, costs and tax context. Treat the table as a research starting point, not a recommendation." },
    { q: "Can NRIs invest in PMS?", a: "Yes. NRIs can invest in PMS subject to FEMA rules and provider-level documentation. Account setup and taxation should be reviewed before investing." },
    { q: "Is PMS better than mutual funds?", a: "PMS is not automatically better. It can provide concentrated active management and direct ownership, but it also has higher minimums, different tax treatment and higher portfolio-specific risk." },
  ],
  related: [
    { title: "PMS Distribution", href: "/pms-advisory", description: "Understand SoHo Wealth's selection, documentation and onboarding process." },
    { title: "SIF vs PMS", href: "/sif-vs-pms", description: "Compare SIF and PMS before choosing your route." },
    { title: "Portfolio Review", href: "/portfolio-review", description: "Review your current allocation before adding PMS." },
  ],
};

export const sifVsPms: LandingPageConfig = {
  slug: "sif-vs-pms",
  title: "SIF vs PMS",
  eyebrow: "Investment Comparison",
  h1: "SIF vs PMS:",
  highlightedH1: "Which One Fits Your Portfolio?",
  intro: "SIF and PMS both target investors looking beyond traditional mutual funds, but they differ in minimum investment, structure, transparency, customization and tax experience. This page helps you compare both before choosing.",
  primaryCta: "Compare SIF and PMS",
  secondaryCta: "WhatsApp for Guidance",
  serviceName: "SIF vs PMS Advisory",
  serviceDescription: "Comparison-led advisory for investors deciding between Specialized Investment Funds and Portfolio Management Services in India.",
  serviceType: "Investment Comparison Advisory",
  leadSource: "sif-vs-pms page",
  formHeading: "Get a SIF vs PMS Recommendation",
  formTitle: "Choose the Right Route",
  formCopy: "Tell us your portfolio size, goals and risk comfort. We will help you decide whether SIF, PMS or a simpler mutual fund route makes sense.",
  formBullets: [
    "SIF vs PMS suitability map",
    "Minimum investment and liquidity review",
    "Risk, transparency and tax comparison",
    "Portfolio fit recommendation",
    "Onboarding support if suitable",
  ],
  sections: [
    {
      eyebrow: "Simple View",
      heading: "SIF Sits Between Mutual Funds and PMS",
      copy: "Specialized Investment Funds were introduced to give investors access to advanced strategies at a lower minimum than PMS. PMS remains more customized and directly owned, but it starts at a much higher capital threshold.",
      cards: [
        { title: "Choose SIF When", description: "You want advanced strategies like long-short or derivatives exposure from Rs. 10 lakh within a regulated fund structure." },
        { title: "Choose PMS When", description: "You can allocate Rs. 50 lakh or more and want a concentrated portfolio with direct stock ownership." },
        { title: "Choose Neither When", description: "Your goals are simple, your portfolio is smaller or you need high liquidity. A mutual fund portfolio may be better." },
      ],
    },
    {
      heading: "Decision Factors",
      bullets: [
        "Portfolio size: SIF starts at Rs. 10 lakh, PMS starts at Rs. 50 lakh",
        "Customization: PMS can offer more personalization than SIF",
        "Transparency: SIF follows a fund-style framework; PMS gives stock-level ownership",
        "Tax: PMS trades can trigger investor-level capital gains; SIF taxation depends on product structure",
        "Use case: SIF can be a bridge between mutual funds and PMS; PMS can be a core HNI allocation",
      ],
    },
  ],
  comparison: {
    heading: "SIF vs PMS Comparison",
    columns: [
      { key: "sif", label: "SIF" },
      { key: "pms", label: "PMS" },
    ],
    highlightKey: "sif",
    rows: [
      { feature: "Minimum investment", sif: "Rs. 10 lakh", pms: "Rs. 50 lakh" },
      { feature: "Structure", sif: "Fund-style regulated product", pms: "Managed portfolio in investor's name" },
      { feature: "Direct stock ownership", sif: "No", pms: "Yes" },
      { feature: "Customization", sif: "Limited to chosen scheme", pms: "Higher, depending on provider" },
      { feature: "Advanced strategies", sif: "Yes, depending on scheme", pms: "Yes, depending on mandate" },
      { feature: "Best for", sif: "Investors graduating beyond mutual funds", pms: "HNIs allocating Rs. 50 lakh or more" },
    ],
  },
  faqs: [
    { q: "What is the main difference between SIF and PMS?", a: "The biggest differences are minimum investment and structure. SIF starts at Rs. 10 lakh and works like a regulated fund-style product, while PMS starts at Rs. 50 lakh and manages securities in the investor's own demat account." },
    { q: "Is SIF safer than PMS?", a: "Not necessarily. Both carry market risk. SIF may be more accessible and fund-like, while PMS may be more concentrated. Suitability depends on the scheme, strategy and investor profile." },
    { q: "Can I invest in both SIF and PMS?", a: "Yes. Some investors may use SIF as a satellite allocation and PMS as a larger concentrated equity allocation. This should be decided after reviewing the overall portfolio." },
    { q: "Should I choose SIF or PMS if I have Rs. 25 lakh?", a: "At Rs. 25 lakh, SIF may be accessible while PMS is not, because PMS requires Rs. 50 lakh. But the right choice also depends on liquidity needs, risk appetite and existing mutual fund allocation." },
  ],
  related: [
    { title: "SIF Advisory", href: "/sif", description: "Understand Specialized Investment Funds in detail." },
    { title: "PMS Advisory", href: "/pms-advisory", description: "Compare PMS strategies from Rs. 50 lakh." },
    { title: "Mutual Funds", href: "/mutual-funds", description: "Build a simpler goal-based portfolio when PMS or SIF is not suitable." },
  ],
};
