import type { LandingPageConfig } from "./LandingPageClient";

export const wealthManagementHyderabad: LandingPageConfig = {
  slug: "wealth-management-hyderabad",
  title: "Wealth Management Hyderabad",
  eyebrow: "Wealth Advisor in Hyderabad",
  h1: "Wealth Management in Hyderabad for",
  highlightedH1: "HNIs, Founders, Families & NRIs.",
  intro: "SoHo Wealth is a Hyderabad-based boutique wealth advisory firm for investors who need more than product sales: portfolio review, PMS, SIF, AIF, mutual funds, NRI advisory, global investing and pre-IPO access under one relationship.",
  primaryCta: "Book a Hyderabad Consultation",
  secondaryCta: "WhatsApp a Wealth Advisor",
  serviceName: "Wealth Management in Hyderabad",
  serviceDescription: "Boutique wealth management in Hyderabad for HNIs, NRIs, family offices, founders and professionals across PMS, SIF, AIF, mutual funds, global investing and pre-IPO opportunities.",
  serviceType: "Wealth Management",
  leadSource: "wealth-management-hyderabad page",
  formHeading: "Book a Wealth Management Consultation",
  formTitle: "Get a Clear View of Your Wealth",
  formCopy: "Bring your portfolio, goals and questions. We will help you identify gaps, risks, fees and the right next step.",
  formBullets: [
    "Portfolio health check",
    "Asset allocation and risk review",
    "PMS, SIF, AIF and mutual fund fitment",
    "NRI and global investing considerations",
    "Direct consultation with Kiran Dutta",
  ],
  sections: [
    {
      eyebrow: "Why SoHo Wealth",
      heading: "A Boutique Alternative to Bank-Led Wealth Management",
      copy: "Many investors in Hyderabad are served by banks or product-led distributors. SoHo Wealth is built for a different conversation: understanding your whole financial picture and choosing products only when they fit.",
      cards: [
        { title: "Independent Product Selection", description: "We are not tied to one AMC, PMS or AIF provider. The goal is to match your allocation to your risk profile, horizon and liquidity needs." },
        { title: "Hyderabad-First, India-Wide", description: "Meet in person in Hyderabad or work with us remotely across India and overseas as an NRI." },
        { title: "Full-Stack Advisory", description: "From mutual funds to PMS, SIF, AIF, pre-IPO and global investing, we help organize the full portfolio." },
        { title: "Portfolio Review First", description: "Before recommending anything, we look at what you already own, where risk is concentrated and what is underperforming." },
        { title: "Transparent Follow-Through", description: "You get ongoing monitoring, reviews and simple explanations instead of one-time product placement." },
        { title: "Registered Distribution", description: "SoHo Wealth is AMFI and APMI registered, with compliance-first communication around market risk." },
      ],
    },
    {
      heading: "Who We Help",
      bullets: [
        "HNIs and families with investable portfolios above Rs. 25 lakh",
        "Founders, business owners and senior professionals in Hyderabad",
        "Doctors, CXOs and tech professionals with concentrated wealth or RSUs",
        "NRIs who want India investments managed with FEMA and tax awareness",
        "Investors comparing PMS, SIF, AIF and mutual funds before committing capital",
      ],
    },
  ],
  comparison: {
    heading: "How SoHo Wealth Compares",
    columns: [
      { key: "bank", label: "Typical Bank RM" },
      { key: "soho", label: "SoHo Wealth" },
    ],
    highlightKey: "soho",
    rows: [
      { feature: "Product range", bank: "Often bank-led", soho: "Open architecture across MF, PMS, SIF, AIF and more" },
      { feature: "Starting point", bank: "Product pitch", soho: "Portfolio review and goal mapping" },
      { feature: "Local access", bank: "Branch or RM availability", soho: "Hyderabad-based plus remote support" },
      { feature: "Ongoing review", bank: "Varies by RM", soho: "Structured portfolio monitoring" },
    ],
  },
  faqs: [
    { q: "Who is a good fit for SoHo Wealth in Hyderabad?", a: "SoHo Wealth is best suited for HNIs, families, founders, senior professionals and NRIs who want a structured portfolio review and guidance across mutual funds, PMS, SIF, AIF, pre-IPO and global investing." },
    { q: "Is the first consultation free?", a: "Yes. The first portfolio review or consultation is complimentary and no-obligation. It is meant to help you understand your current portfolio and possible next steps." },
    { q: "Do you work only with Hyderabad clients?", a: "No. SoHo Wealth is based in Hyderabad but works with clients across India and NRIs globally through video consultations." },
    { q: "What is the minimum portfolio size?", a: "The complimentary review is most useful for investors with Rs. 25 lakh or more in investable assets. Product minimums differ: SIF starts at Rs. 10 lakh, PMS at Rs. 50 lakh and AIF at Rs. 1 crore." },
  ],
  related: [
    { title: "PMS Advisory", href: "/pms-advisory", description: "Compare concentrated listed-equity PMS strategies from Rs. 50 lakh." },
    { title: "SIF Advisory", href: "/sif", description: "Explore SEBI-regulated SIFs from Rs. 10 lakh." },
    { title: "Free Portfolio Review", href: "/portfolio-review", description: "Get a 30-minute review of your current investments." },
  ],
};

export const bestPmsHyderabad: LandingPageConfig = {
  slug: "best-pms-in-hyderabad",
  title: "Best PMS in Hyderabad",
  eyebrow: "PMS Advisor in Hyderabad",
  h1: "Looking for the Best PMS in Hyderabad?",
  highlightedH1: "Compare Before You Invest.",
  intro: "The best PMS for you is not simply the one with the highest trailing return. It is the strategy that fits your risk appetite, time horizon, tax situation and existing portfolio. SoHo Wealth helps Hyderabad investors compare PMS strategies objectively.",
  primaryCta: "Compare PMS Strategies",
  secondaryCta: "WhatsApp About PMS",
  serviceName: "PMS Advisory in Hyderabad",
  serviceDescription: "Independent PMS advisory in Hyderabad for HNIs comparing portfolio management services, manager track records, drawdowns, fees, taxation and portfolio fit.",
  serviceType: "Portfolio Management Services Advisory",
  leadSource: "best-pms-in-hyderabad page",
  formHeading: "Book a PMS Comparison Call",
  formTitle: "Shortlist the Right PMS Strategy",
  formCopy: "We will help you compare strategy style, manager quality, volatility, fees and portfolio fit before you commit Rs. 50 lakh or more.",
  formBullets: [
    "PMS suitability check",
    "Manager and strategy comparison",
    "Fee, exit load and tax review",
    "Risk and drawdown discussion",
    "Implementation support",
  ],
  sections: [
    {
      eyebrow: "Evaluation Framework",
      heading: "How to Choose a PMS Beyond Past Returns",
      copy: "PMS performance can look attractive in one market cycle and struggle in another. A careful PMS selection process should look at repeatability, downside control, concentration and fit.",
      cards: [
        { title: "Strategy Style", description: "Large cap, multi cap, small cap, quant, thematic and long-short PMS strategies behave very differently." },
        { title: "Drawdown History", description: "A strategy's worst periods often tell you more about suitability than its best periods." },
        { title: "Portfolio Concentration", description: "Most PMS portfolios hold fewer stocks than mutual funds, which can increase both upside and volatility." },
        { title: "Fund Manager Continuity", description: "Tenure, process discipline and team depth matter when evaluating repeatability." },
        { title: "Fees and Exit Loads", description: "Fixed fees, performance fees, hurdle rates and exit terms can materially affect net returns." },
        { title: "Tax Impact", description: "PMS investors own the underlying securities, so portfolio churn can create investor-level capital gains." },
      ],
    },
    {
      heading: "Who Should Consider PMS?",
      bullets: [
        "Investors with at least Rs. 50 lakh available for one PMS strategy",
        "HNIs who can handle higher volatility than diversified mutual funds",
        "Investors seeking direct stock ownership and a concentrated portfolio",
        "Families looking to complement mutual funds with active manager exposure",
        "NRIs investing through compliant account structures",
      ],
    },
  ],
  comparison: {
    heading: "PMS vs Mutual Funds",
    columns: [
      { key: "mf", label: "Mutual Fund" },
      { key: "pms", label: "PMS" },
    ],
    highlightKey: "pms",
    rows: [
      { feature: "Minimum investment", mf: "Can start from SIP levels", pms: "Rs. 50 lakh minimum" },
      { feature: "Portfolio structure", mf: "Pooled fund units", pms: "Stocks held in investor's demat" },
      { feature: "Concentration", mf: "Usually 40-80 securities", pms: "Often 15-25 securities" },
      { feature: "Tax treatment", mf: "Tax when units are sold", pms: "Capital gains from manager trades" },
      { feature: "Customization", mf: "Limited", pms: "Higher, depending on mandate" },
    ],
  },
  faqs: [
    { q: "What is the minimum amount for PMS in India?", a: "The SEBI-mandated minimum for PMS is Rs. 50 lakh per investor. This applies across PMS providers." },
    { q: "Which PMS is best in Hyderabad?", a: "There is no single best PMS for every investor. The right PMS depends on your risk appetite, time horizon, existing portfolio, tax position and preference for strategy style." },
    { q: "Can NRIs invest in PMS?", a: "Yes. NRIs can invest in PMS subject to FEMA rules and provider-level documentation. Account setup and taxation should be reviewed before investing." },
    { q: "Is PMS better than mutual funds?", a: "PMS is not automatically better. It can provide concentrated active management and direct ownership, but it also has higher minimums, different tax treatment and higher portfolio-specific risk." },
  ],
  related: [
    { title: "PMS Advisory", href: "/pms-advisory", description: "Read the complete PMS advisory overview." },
    { title: "SIF vs PMS", href: "/sif-vs-pms", description: "Compare SIF and PMS before choosing your route." },
    { title: "Portfolio Review", href: "/portfolio-review", description: "Review your current allocation before adding PMS." },
  ],
};

export const sifVsPms: LandingPageConfig = {
  slug: "sif-vs-pms",
  title: "SIF vs PMS",
  eyebrow: "Investment Comparison",
  h1: "SIF vs PMS:",
  highlightedH1: "Which One Fits Your Portfolio?",
  intro: "SIF and PMS both target investors looking beyond traditional mutual funds, but they differ in minimum investment, structure, transparency, customization and tax experience. This page helps you compare both before choosing.",
  primaryCta: "Compare SIF and PMS",
  secondaryCta: "WhatsApp for Guidance",
  serviceName: "SIF vs PMS Advisory",
  serviceDescription: "Comparison-led advisory for investors deciding between Specialized Investment Funds and Portfolio Management Services in India.",
  serviceType: "Investment Comparison Advisory",
  leadSource: "sif-vs-pms page",
  formHeading: "Get a SIF vs PMS Recommendation",
  formTitle: "Choose the Right Route",
  formCopy: "Tell us your portfolio size, goals and risk comfort. We will help you decide whether SIF, PMS or a simpler mutual fund route makes sense.",
  formBullets: [
    "SIF vs PMS suitability map",
    "Minimum investment and liquidity review",
    "Risk, transparency and tax comparison",
    "Portfolio fit recommendation",
    "Onboarding support if suitable",
  ],
  sections: [
    {
      eyebrow: "Simple View",
      heading: "SIF Sits Between Mutual Funds and PMS",
      copy: "Specialized Investment Funds were introduced to give investors access to advanced strategies at a lower minimum than PMS. PMS remains more customized and directly owned, but it starts at a much higher capital threshold.",
      cards: [
        { title: "Choose SIF When", description: "You want advanced strategies like long-short or derivatives exposure from Rs. 10 lakh within a regulated fund structure." },
        { title: "Choose PMS When", description: "You can allocate Rs. 50 lakh or more and want a concentrated portfolio with direct stock ownership." },
        { title: "Choose Neither When", description: "Your goals are simple, your portfolio is smaller or you need high liquidity. A mutual fund portfolio may be better." },
      ],
    },
    {
      heading: "Decision Factors",
      bullets: [
        "Portfolio size: SIF starts at Rs. 10 lakh, PMS starts at Rs. 50 lakh",
        "Customization: PMS can offer more personalization than SIF",
        "Transparency: SIF follows a fund-style framework; PMS gives stock-level ownership",
        "Tax: PMS trades can trigger investor-level capital gains; SIF taxation depends on product structure",
        "Use case: SIF can be a bridge between mutual funds and PMS; PMS can be a core HNI allocation",
      ],
    },
  ],
  comparison: {
    heading: "SIF vs PMS Comparison",
    columns: [
      { key: "sif", label: "SIF" },
      { key: "pms", label: "PMS" },
    ],
    highlightKey: "sif",
    rows: [
      { feature: "Minimum investment", sif: "Rs. 10 lakh", pms: "Rs. 50 lakh" },
      { feature: "Structure", sif: "Fund-style regulated product", pms: "Managed portfolio in investor's name" },
      { feature: "Direct stock ownership", sif: "No", pms: "Yes" },
      { feature: "Customization", sif: "Limited to chosen scheme", pms: "Higher, depending on provider" },
      { feature: "Advanced strategies", sif: "Yes, depending on scheme", pms: "Yes, depending on mandate" },
      { feature: "Best for", sif: "Investors graduating beyond mutual funds", pms: "HNIs allocating Rs. 50 lakh or more" },
    ],
  },
  faqs: [
    { q: "What is the main difference between SIF and PMS?", a: "The biggest differences are minimum investment and structure. SIF starts at Rs. 10 lakh and works like a regulated fund-style product, while PMS starts at Rs. 50 lakh and manages securities in the investor's own demat account." },
    { q: "Is SIF safer than PMS?", a: "Not necessarily. Both carry market risk. SIF may be more accessible and fund-like, while PMS may be more concentrated. Suitability depends on the scheme, strategy and investor profile." },
    { q: "Can I invest in both SIF and PMS?", a: "Yes. Some investors may use SIF as a satellite allocation and PMS as a larger concentrated equity allocation. This should be decided after reviewing the overall portfolio." },
    { q: "Should I choose SIF or PMS if I have Rs. 25 lakh?", a: "At Rs. 25 lakh, SIF may be accessible while PMS is not, because PMS requires Rs. 50 lakh. But the right choice also depends on liquidity needs, risk appetite and existing mutual fund allocation." },
  ],
  related: [
    { title: "SIF Advisory", href: "/sif", description: "Understand Specialized Investment Funds in detail." },
    { title: "PMS Advisory", href: "/pms-advisory", description: "Compare PMS strategies from Rs. 50 lakh." },
    { title: "Mutual Funds", href: "/mutual-funds", description: "Build a simpler goal-based portfolio when PMS or SIF is not suitable." },
  ],
};
