import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, PiggyBank } from "lucide-react";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { FAQSection, type FAQ } from "@/components/seo/FAQSection";
import { JsonLd } from "@/components/seo/JsonLd";
import { PpfCalculator } from "./PpfCalculator";

const canonicalUrl = "https://www.sohowealth.in/tools/ppf-calculator";
const socialImage = "https://www.sohowealth.in/retirement-planning/opengraph-image";
export const metadata: Metadata = { title: "PPF Calculator India 2026 | Maturity Estimate", description: "Estimate a PPF maturity value using your current balance, annual deposits, projection period and an editable interest-rate assumption.", keywords: ["PPF calculator", "PPF calculator India", "PPF maturity calculator", "Public Provident Fund calculator", "PPF interest calculator"], alternates: { canonical: canonicalUrl }, robots: { index: true, follow: true }, openGraph: { title: "PPF Calculator India", description: "Estimate PPF growth with an editable interest-rate assumption.", url: canonicalUrl, type: "website", images: [socialImage] }, twitter: { card: "summary_large_image", title: "PPF Calculator India", description: "Estimate an illustrative Public Provident Fund balance.", images: [socialImage] } };
const faqs: FAQ[] = [
  { q: "How is the PPF maturity estimate calculated?", a: "The calculator adds the annual deposit at the start of each illustrated year and compounds the balance at the annual rate you enter." },
  { q: "What is the current maximum annual PPF deposit?", a: "The current scheme limit is ₹1.5 lakh per financial year. Confirm the latest rules before contributing because limits can change." },
  { q: "Is the PPF interest rate fixed for 15 years?", a: "No. The rate is notified periodically. This calculator keeps it editable and applies one assumed rate only to create a planning illustration." },
  { q: "When does a PPF account mature?", a: "Under the current scheme, it matures after 15 complete financial years from the end of the financial year in which it was opened. Existing-account dates should be checked from the actual opening record." },
];
const schema = { "@context": "https://schema.org", "@type": "WebApplication", name: "PPF Calculator India", url: canonicalUrl, applicationCategory: "FinanceApplication", operatingSystem: "Any", isAccessibleForFree: true, description: "A browser-based PPF maturity calculator with editable balance, deposit, term and rate assumptions.", featureList: ["PPF maturity estimate", "Editable notified-rate assumption", "Deposit and interest breakdown", "No personal data required"], citation: ["https://www.nsiindia.gov.in/InternalPage.aspx?Id_Pk=55", "https://www.nsiindia.gov.in/InternalPage.aspx?Id_Pk=169"], offers: { "@type": "Offer", price: 0, priceCurrency: "INR" }, provider: { "@id": "https://www.sohowealth.in/#organization" } };
export default function PpfCalculatorPage() { return <main className="bg-white pt-20"><JsonLd data={schema} /><Breadcrumbs items={[{ name: "Retirement Planning", href: "/retirement-planning" }, { name: "PPF Calculator", href: "/tools/ppf-calculator" }]} /><section className="bg-[#07192F] py-16 text-white lg:py-24"><div className="container mx-auto max-w-5xl px-6 text-center lg:px-8"><span className="inline-flex items-center gap-2 rounded-full border border-[#C9A84C]/40 bg-[#C9A84C]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.15em] text-[#E5CB83]"><PiggyBank className="h-4 w-4" /> Free PPF planning tool</span><h1 className="mx-auto mt-6 max-w-4xl font-display text-4xl font-semibold md:text-6xl">PPF calculator for India.</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-white/70">Estimate a future Public Provident Fund balance without treating the current notified rate as a permanent 15-year promise.</p></div></section><PpfCalculator /><section className="bg-white py-16"><div className="container mx-auto max-w-4xl px-6 lg:px-8"><h2 className="font-display text-3xl font-semibold text-[#0B1F3A]">Put PPF in the complete retirement portfolio</h2><p className="mt-4 leading-relaxed text-slate-600">PPF can provide long-term fixed-income exposure, but it has a deposit ceiling and rule-based access. Review it alongside EPF, NPS and liquid reserves before deciding what role it should play.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/insights/epf-vs-ppf-vs-nps" className="inline-flex items-center justify-center rounded-xl bg-[#0B1F3A] px-6 py-3 text-sm font-bold text-white">Compare EPF, PPF and NPS <ArrowRight className="ml-2 h-4 w-4" /></Link><Link href="/tools/retirement-calculator" className="inline-flex items-center justify-center rounded-xl border border-slate-300 px-6 py-3 text-sm font-bold text-[#0B1F3A]">Calculate the retirement gap</Link></div></div></section><FAQSection faqs={faqs} heading="PPF Calculator FAQs" background="#F7F8FA" /></main>; }
