"use client";
import { useMemo, useState } from "react";
const inr=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
function Field({label,value,onChange,suffix}:{label:string;value:number;onChange:(v:number)=>void;suffix:string}){return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><div className="relative"><input type="number" min="0" value={value} onChange={e=>onChange(Number(e.target.value)||0)} className="w-full rounded-xl border border-slate-200 px-4 py-3 pr-16 outline-none focus:ring-2 focus:ring-[#C9A84C]"/><span className="absolute right-4 top-3.5 text-sm text-slate-400">{suffix}</span></div></label>}
export function PropertyCalculators(){
 const [mode,setMode]=useState<"emi"|"yield"|"cost"|"afford">("emi"),[price,setPrice]=useState(15000000),[down,setDown]=useState(3000000),[rate,setRate]=useState(8.5),[years,setYears]=useState(20),[rent,setRent]=useState(45000),[annualCosts,setAnnualCosts]=useState(120000),[registrationRate,setRegistrationRate]=useState(7.5),[other,setOther]=useState(300000);
 const result=useMemo(()=>{const loan=Math.max(0,price-down),n=years*12,r=rate/1200,emi=r&&n?loan*r*(1+r)**n/((1+r)**n-1):n?loan/n:0;return{loan,emi,gross:price?(rent*12/price)*100:0,net:price?((rent*12-annualCosts)/price)*100:0,acquisition:price+(price*registrationRate/100)+other,affordable:down/.2}},[price,down,rate,years,rent,annualCosts,registrationRate,other]);
 const modes=[{id:"emi",label:"Home-loan EMI"},{id:"yield",label:"Rental yield"},{id:"cost",label:"Acquisition cost"},{id:"afford",label:"Affordability"}] as const;
 return <div><div className="flex flex-wrap gap-2">{modes.map(item=><button key={item.id} onClick={()=>setMode(item.id)} className={`rounded-full px-4 py-2 text-sm font-bold ${mode===item.id?"bg-[#0B1F3A] text-white":"border border-slate-200 bg-white text-slate-600"}`}>{item.label}</button>)}</div><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_.8fr]"><div className="grid gap-5 rounded-3xl border border-slate-200 bg-white p-6 md:grid-cols-2 md:p-8"><Field label="Property price" value={price} onChange={setPrice} suffix="₹"/>{mode==="emi"&&<><Field label="Down payment" value={down} onChange={setDown} suffix="₹"/><Field label="Interest rate" value={rate} onChange={setRate} suffix="%"/><Field label="Loan tenure" value={years} onChange={setYears} suffix="years"/></>}{mode==="yield"&&<><Field label="Expected monthly rent" value={rent} onChange={setRent} suffix="₹"/><Field label="Annual costs & vacancy" value={annualCosts} onChange={setAnnualCosts} suffix="₹"/></>}{mode==="cost"&&<><Field label="Indicative duties & registration" value={registrationRate} onChange={setRegistrationRate} suffix="%"/><Field label="Other acquisition costs" value={other} onChange={setOther} suffix="₹"/></>}{mode==="afford"&&<><Field label="Available down payment" value={down} onChange={setDown} suffix="₹"/><p className="self-end text-sm leading-relaxed text-slate-500">Assumes a 20% down payment. Keep transaction costs, interiors and emergency liquidity separate.</p></>}</div><div className="rounded-3xl bg-[#0B1F3A] p-8 text-white"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#C9A84C]">Illustrative result</p>{mode==="emi"&&<><p className="mt-5 text-sm text-white/60">Monthly EMI</p><p className="mt-1 font-display text-4xl font-semibold text-[#C9A84C]">{inr.format(result.emi)}</p><p className="mt-5 text-sm text-white/60">Loan amount: {inr.format(result.loan)}</p></>}{mode==="yield"&&<><p className="mt-5 text-sm text-white/60">Gross rental yield</p><p className="mt-1 font-display text-4xl font-semibold text-[#C9A84C]">{result.gross.toFixed(2)}%</p><p className="mt-5 text-sm text-white/60">Indicative net yield: {result.net.toFixed(2)}%</p></>}{mode==="cost"&&<><p className="mt-5 text-sm text-white/60">Estimated acquisition cost</p><p className="mt-1 font-display text-4xl font-semibold text-[#C9A84C]">{inr.format(result.acquisition)}</p></>}{mode==="afford"&&<><p className="mt-5 text-sm text-white/60">Illustrative property budget</p><p className="mt-1 font-display text-4xl font-semibold text-[#C9A84C]">{inr.format(result.affordable)}</p></>}<p className="mt-8 border-t border-white/10 pt-5 text-xs leading-relaxed text-white/45">Educational estimate only. Confirm charges, eligibility, taxes, vacancy and costs with qualified professionals.</p></div></div></div>
}
