import type { LeadIntentConfig } from "@/lib/leads/types";
import type { LeadFormState } from "./LeadStepOne";

type Props = { config: LeadIntentConfig; form: LeadFormState; errors: Record<string, string>; loading: boolean; onChange: (name: keyof LeadFormState, value: string | boolean) => void; onBack: () => void; onSubmit: (event: React.FormEvent) => void };

export function LeadStepTwo({ config, form, errors, loading, onChange, onBack, onSubmit }: Props) {
  const input = "mt-1.5 w-full rounded-lg border border-white/20 bg-white/10 px-4 py-3 text-white placeholder:text-white/45 focus:outline-none focus:ring-2 focus:ring-[#C9A84C]";
  return (
    <form onSubmit={onSubmit} className="space-y-5">
      <div><label htmlFor="lead-portfolio" className="text-sm font-semibold text-white/80">Investable portfolio range</label><select id="lead-portfolio" value={form.portfolio_size} onChange={(e) => onChange("portfolio_size", e.target.value)} aria-invalid={Boolean(errors.portfolio_size)} className={input}><option className="text-slate-900" value="">Select a range</option>{(config.portfolioOptions || []).map((value) => <option className="text-slate-900" key={value}>{value}</option>)}</select>{errors.portfolio_size ? <p className="mt-1 text-xs text-red-300">{errors.portfolio_size}</p> : null}</div>
      <div><label htmlFor="lead-email" className="text-sm font-semibold text-white/80">Email <span className="font-normal text-white/50">(optional when mobile is supplied)</span></label><input id="lead-email" type="email" inputMode="email" autoComplete="email" value={form.email} onChange={(e) => onChange("email", e.target.value)} aria-invalid={Boolean(errors.email)} className={input} placeholder="you@example.com" />{errors.email ? <p className="mt-1 text-xs text-red-300">{errors.email}</p> : null}</div>
      <fieldset><legend className="text-sm font-semibold text-white/80">Residency</legend><div className="mt-2 flex gap-3">{(["resident", "nri"] as const).map((value) => <button type="button" key={value} onClick={() => onChange("resident_status", value)} aria-pressed={form.resident_status === value} className={`min-h-11 rounded-lg border px-5 py-2 text-sm font-semibold ${form.resident_status === value ? "border-[#C9A84C] bg-[#C9A84C] text-[#0B1F3A]" : "border-white/20 text-white/70"}`}>{value === "nri" ? "NRI" : "Resident"}</button>)}</div></fieldset>
      <div><label htmlFor="lead-call-time" className="text-sm font-semibold text-white/80">Preferred call window</label><select id="lead-call-time" value={form.call_time} onChange={(e) => onChange("call_time", e.target.value)} className={input}><option className="text-slate-900" value="">No preference</option>{["Morning 9–12", "Afternoon 12–4", "Evening 4–7"].map((value) => <option className="text-slate-900" key={value}>{value}</option>)}</select></div>
      {config.qualification ? <div><label htmlFor="lead-qualification" className="text-sm font-semibold text-white/80">{config.qualification.label}</label><select id="lead-qualification" value={form.qualification_value} onChange={(e) => onChange("qualification_value", e.target.value)} className={input}><option className="text-slate-900" value="">Select one (optional)</option>{config.qualification.options.map((value) => <option className="text-slate-900" key={value}>{value}</option>)}</select></div> : null}
      <div><label htmlFor="lead-message" className="text-sm font-semibold text-white/80">Anything useful to know? <span className="font-normal text-white/50">(optional)</span></label><textarea id="lead-message" value={form.message} onChange={(e) => onChange("message", e.target.value)} maxLength={1000} rows={3} className={input} /></div>
      <div className="absolute left-[-10000px]" aria-hidden="true"><label htmlFor="lead-website">Website</label><input id="lead-website" tabIndex={-1} autoComplete="off" value={form.website} onChange={(e) => onChange("website", e.target.value)} /></div>
      <label className="flex items-start gap-3 text-sm leading-relaxed text-white/70"><input type="checkbox" checked={form.privacy_consent} onChange={(e) => onChange("privacy_consent", e.target.checked)} aria-invalid={Boolean(errors.privacy_consent)} className="mt-1 h-4 w-4 accent-[#C9A84C]" /><span>I agree that SoHo Wealth may use these details to respond to this request. See the <a className="underline" href="/privacy-policy">privacy policy</a>.</span></label>{errors.privacy_consent ? <p className="text-xs text-red-300">{errors.privacy_consent}</p> : null}
      <div className="flex gap-3"><button type="button" onClick={onBack} className="min-h-11 rounded-lg border border-white/25 px-5 py-3 font-semibold text-white">Back</button><button type="submit" disabled={loading} className="min-h-11 flex-1 rounded-lg bg-[#C9A84C] px-5 py-3 font-semibold text-[#0B1F3A] disabled:opacity-60">{loading ? "Sending request…" : config.primaryButton}</button></div>
    </form>
  );
}
