import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BriefcaseBusiness } from "lucide-react";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { FAQSection, type FAQ } from "@/components/seo/FAQSection";
import { JsonLd } from "@/components/seo/JsonLd";
import { EpfCalculator } from "./EpfCalculator";

const canonicalUrl = "https://www.sohowealth.in/tools/epf-calculator";
const socialImage = "https://www.sohowealth.in/retirement-planning/opengraph-image";
export const metadata: Metadata = { title: "EPF Calculator India 2026 | Retirement Balance", description: "Estimate your future EPF balance using current savings, monthly EPF credits, contribution increases, years and an editable interest-rate assumption.", keywords: ["EPF calculator", "EPF calculator India", "EPF maturity calculator", "provident fund calculator", "EPF retirement calculator"], alternates: { canonical: canonicalUrl }, robots: { index: true, follow: true }, openGraph: { title: "EPF Calculator India", description: "Estimate future EPF savings with editable contributions and interest assumptions.", url: canonicalUrl, type: "website", images: [socialImage] }, twitter: { card: "summary_large_image", title: "EPF Calculator India", description: "Estimate an illustrative EPF balance for retirement.", images: [socialImage] } };
const faqs: FAQ[] = [
  { q: "How does this EPF calculator work?", a: "It adds the monthly EPF credit you enter, increases that credit annually by your chosen step-up and applies the entered annual interest assumption over the selected period." },
  { q: "What should I enter as the monthly EPF contribution?", a: "Use the total amount actually credited to EPF in your passbook. Do not automatically add the full employer contribution because an applicable portion may go to EPS." },
  { q: "Is the EPF interest rate guaranteed for the next 20 years?", a: "No. EPF interest is declared for the applicable period and can change. Edit the assumption and test more than one rate." },
  { q: "Will this match my EPFO passbook exactly?", a: "No. It is a planning estimate. Actual credit timing, eligible wages, EPS allocation, withdrawals, service records and EPFO interest-crediting rules affect the balance." },
];
const schema = { "@context": "https://schema.org", "@type": "WebApplication", name: "EPF Calculator India", url: canonicalUrl, applicationCategory: "FinanceApplication", operatingSystem: "Any", isAccessibleForFree: true, description: "A browser-based EPF retirement-balance calculator with editable contribution and interest assumptions.", featureList: ["Future EPF balance", "Contribution step-up", "Editable interest assumption", "No personal data required"], citation: ["https://www.epfindia.gov.in/site_en/FAQ.php"], offers: { "@type": "Offer", price: 0, priceCurrency: "INR" }, provider: { "@id": "https://www.sohowealth.in/#organization" } };
export default function EpfCalculatorPage() { return <main className="bg-white pt-20"><JsonLd data={schema} /><Breadcrumbs items={[{ name: "Retirement Planning", href: "/retirement-planning" }, { name: "EPF Calculator", href: "/tools/epf-calculator" }]} /><section className="bg-[#07192F] py-16 text-white lg:py-24"><div className="container mx-auto max-w-5xl px-6 text-center lg:px-8"><span className="inline-flex items-center gap-2 rounded-full border border-[#C9A84C]/40 bg-[#C9A84C]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.15em] text-[#E5CB83]"><BriefcaseBusiness className="h-4 w-4" /> Free EPF planning tool</span><h1 className="mx-auto mt-6 max-w-4xl font-display text-4xl font-semibold md:text-6xl">EPF calculator for retirement planning.</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-relaxed text-white/70">Estimate how your current EPF balance and future monthly credits could grow—while keeping every assumption visible and editable.</p></div></section><EpfCalculator /><section className="bg-white py-16"><div className="container mx-auto max-w-4xl px-6 lg:px-8"><h2 className="font-display text-3xl font-semibold text-[#0B1F3A]">EPF is one part of the retirement plan</h2><p className="mt-4 leading-relaxed text-slate-600">After estimating EPF, combine it with PPF, NPS and other goal-linked assets only once. Then calculate the spending corpus and contribution gap for the household.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/insights/epf-vs-ppf-vs-nps" className="inline-flex items-center justify-center rounded-xl bg-[#0B1F3A] px-6 py-3 text-sm font-bold text-white">Compare EPF, PPF and NPS <ArrowRight className="ml-2 h-4 w-4" /></Link><Link href="/tools/retirement-calculator" className="inline-flex items-center justify-center rounded-xl border border-slate-300 px-6 py-3 text-sm font-bold text-[#0B1F3A]">Calculate the retirement gap</Link></div></div></section><FAQSection faqs={faqs} heading="EPF Calculator FAQs" background="#F7F8FA" /></main>; }
