export type PmsPerformancePeriod = "1 Month" | "3 Months" | "6 Months";

export type PmsPerformanceLeader = {
  rank: number;
  period: PmsPerformancePeriod;
  provider: string;
  strategyName: string;
  strategy: string;
  serviceType: string;
  returnPct: number;
  aumCr: number;
  oneYearPct: number | null;
  iaInsightUrl: string;
};

export const pmsPerformanceMeta = {
  asOnDate: "31 May 2026",
  downloadedOn: "2 June 2026",
  sourceName: "APMI IA Performance Report",
  sourceUrl: "https://www.apmiindia.org/apmi/welcomeiaperformance.htm?action=PMSmenu",
  providerCount: 498,
  investmentApproachCount: 1434,
};

export const pmsPerformanceLeaders: Record<PmsPerformancePeriod, PmsPerformanceLeader[]> = {
  "1 Month": [
    {
      rank: 1,
      period: "1 Month",
      provider: "Ghalla Bhansali Stock Brokers Pvt Ltd",
      strategyName: "KINETIC",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 13.89,
      aumCr: 83.03,
      oneYearPct: 3.38,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=1392",
    },
    {
      rank: 2,
      period: "1 Month",
      provider: "PRP Edge Wealth Pvt Ltd",
      strategyName: "Alphaa factor Investing Fund-ND",
      strategy: "Equity",
      serviceType: "Non Discretionary",
      returnPct: 13.56,
      aumCr: 0.64,
      oneYearPct: null,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=2208",
    },
    {
      rank: 3,
      period: "1 Month",
      provider: "Ghalla Bhansali Stock Brokers Pvt Ltd",
      strategyName: "ACTIVE",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 13.12,
      aumCr: 9.38,
      oneYearPct: 0.58,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=1380",
    },
    {
      rank: 4,
      period: "1 Month",
      provider: "Ghalla Bhansali Stock Brokers Pvt Ltd",
      strategyName: "UNIQUE",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 12.96,
      aumCr: 18.79,
      oneYearPct: 1.4,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=1405",
    },
    {
      rank: 5,
      period: "1 Month",
      provider: "Ghalla Bhansali Stock Brokers Pvt Ltd",
      strategyName: "DISCOVERY",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 12.96,
      aumCr: 18.79,
      oneYearPct: 1.4,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=1383",
    },
  ],
  "3 Months": [
    {
      rank: 1,
      period: "3 Months",
      provider: "Ghalla Bhansali Stock Brokers Pvt Ltd",
      strategyName: "KINETIC",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 20.84,
      aumCr: 83.03,
      oneYearPct: 3.38,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=1392",
    },
    {
      rank: 2,
      period: "3 Months",
      provider: "Ghalla Bhansali Stock Brokers Pvt Ltd",
      strategyName: "RAW PEARL",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 18.57,
      aumCr: 15.67,
      oneYearPct: 1.14,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=1399",
    },
    {
      rank: 3,
      period: "3 Months",
      provider: "Ghalla Bhansali Stock Brokers Pvt Ltd",
      strategyName: "HIGH RISER",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 18.29,
      aumCr: 21.09,
      oneYearPct: 4.12,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=1386",
    },
    {
      rank: 4,
      period: "3 Months",
      provider: "Ghalla Bhansali Stock Brokers Pvt Ltd",
      strategyName: "UNIQUE",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 18.28,
      aumCr: 18.79,
      oneYearPct: 1.4,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=1405",
    },
    {
      rank: 5,
      period: "3 Months",
      provider: "Ghalla Bhansali Stock Brokers Pvt Ltd",
      strategyName: "DISCOVERY",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 18.28,
      aumCr: 18.79,
      oneYearPct: 1.4,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=1383",
    },
  ],
  "6 Months": [
    {
      rank: 1,
      period: "6 Months",
      provider: "PRP Edge Wealth Pvt Ltd",
      strategyName: "Alphaa factor Investing Fund-ND",
      strategy: "Equity",
      serviceType: "Non Discretionary",
      returnPct: 13.38,
      aumCr: 0.64,
      oneYearPct: null,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=2208",
    },
    {
      rank: 2,
      period: "6 Months",
      provider: "Ghalla Bhansali Stock Brokers Pvt Ltd",
      strategyName: "KINETIC",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 11.81,
      aumCr: 83.03,
      oneYearPct: 3.38,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=1392",
    },
    {
      rank: 3,
      period: "6 Months",
      provider: "Ohm Portfolio Equi Research Private Limited",
      strategyName: "Ohm Growth",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 11.12,
      aumCr: 686.95,
      oneYearPct: 15.57,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=642",
    },
    {
      rank: 4,
      period: "6 Months",
      provider: "Ghalla Bhansali Stock Brokers Pvt Ltd",
      strategyName: "GROWTH",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 10.18,
      aumCr: 20.8,
      oneYearPct: 3.34,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=1385",
    },
    {
      rank: 5,
      period: "6 Months",
      provider: "Ghalla Bhansali Stock Brokers Pvt Ltd",
      strategyName: "HIGH RISER",
      strategy: "Equity",
      serviceType: "Discretionary",
      returnPct: 10.09,
      aumCr: 21.09,
      oneYearPct: 4.12,
      iaInsightUrl: "https://www.apmiindia.org/apmi/IaInsight.htm?IAID=1386",
    },
  ],
};
